# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_3-t8KjkLJCJQCcRI8JXRz3b97L7UJ0J
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Set style for visualizations
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

# Load the dataset
df = pd.read_csv('asia_cup_2025_complete_dataset.csv')

# Create enhanced dataframe
df['Date'] = pd.to_datetime(df['Date'])
df['Day_of_Week'] = df['Date'].dt.day_name()
df['Month'] = df['Date'].dt.month
df['Match_Sequence'] = df.index + 1

# Extract win margin values - handle tied matches
df['Win_Margin_Value'] = df['Win_Margin'].str.extract(r'(\d+)').astype(float)
df['Win_Type'] = df['Result'].apply(lambda x: 'wickets' if 'wkts' in x or 'wickets' in x.lower()
                                     else 'runs' if 'runs' in x.lower()
                                     else 'Super Over' if 'super over' in x.lower() or 'Super Over' in x
                                     else 'Tie' if 'tied' in x.lower() else 'Other')

# Calculate total boundaries
df['Total_Boundaries'] = df['Total_Fours'] + df['Total_Sixes']

print("=" * 80)
print("COMPREHENSIVE EDA WITH VISUALIZATIONS - ASIA CUP 2025")
print("=" * 80)

# 1. TEAM PERFORMANCE ANALYSIS WITH GRAPHS
print("\n1. TEAM PERFORMANCE ANALYSIS")
print("-" * 40)

# Get all unique teams
all_teams = pd.concat([df['Team1'], df['Team2']]).unique()

# Calculate wins for each team with proper tie handling
wins = {}
losses = {}
matches_played = {}

for team in all_teams:
    matches_played[team] = len(df[(df['Team1'] == team) | (df['Team2'] == team)])
    wins[team] = 0
    losses[team] = 0

for idx, row in df.iterrows():
    result = row['Result'].lower()
    team1 = row['Team1']
    team2 = row['Team2']

    if 'won' in result:
        # Extract winner from result
        winner_text = row['Result'].split(' won')[0].strip()
        # Handle special case of tied match with super over
        if 'tied' in result:
            # Extract winner from parentheses
            if '(' in row['Result']:
                winner_text = row['Result'].split('(')[-1].split(')')[0].replace('Won', '').strip()

        # Find the actual winner
        if winner_text == team1:
            winner = team1
            loser = team2
        elif winner_text == team2:
            winner = team2
            loser = team1
        else:
            # Try to match by partial name
            if winner_text in team1:
                winner = team1
                loser = team2
            elif winner_text in team2:
                winner = team2
                loser = team1
            else:
                continue  # Skip if we can't determine winner

        wins[winner] = wins.get(winner, 0) + 1
        losses[loser] = losses.get(loser, 0) + 1
    elif 'tied' in result and 'won' not in result:
        # Both teams get 0.5 for a tie
        wins[team1] = wins.get(team1, 0) + 0.5
        wins[team2] = wins.get(team2, 0) + 0.5
        # No loser in a tie

# Create DataFrame for team stats
team_stats = pd.DataFrame({
    'Team': list(all_teams),
    'Matches': [matches_played.get(team, 0) for team in all_teams],
    'Wins': [wins.get(team, 0) for team in all_teams],
    'Losses': [losses.get(team, 0) for team in all_teams]
})
team_stats['Win_Percentage'] = (team_stats['Wins'] / team_stats['Matches'] * 100).round(1)

# Visualization 1: Wins by Team (Bar Chart)
plt.figure(figsize=(12, 6))
team_stats_sorted = team_stats.sort_values('Wins', ascending=False)
bars = plt.bar(team_stats_sorted['Team'], team_stats_sorted['Wins'], color='#2E86AB')
plt.title('Number of Wins by Each Team', fontsize=16, fontweight='bold')
plt.xlabel('Teams', fontsize=12)
plt.ylabel('Number of Wins', fontsize=12)
plt.xticks(rotation=45, ha='right')
# Add value labels on bars
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height + 0.1,
             f'{height:.1f}', ha='center', va='bottom')
plt.tight_layout()
plt.savefig('1_wins_by_team.png', dpi=300, bbox_inches='tight')
plt.show()

# Visualization 2: Win Percentage (Pie Chart)
plt.figure(figsize=(10, 8))
# Use only whole wins for pie chart
wins_for_pie = team_stats.copy()
wins_for_pie['Wins_Whole'] = wins_for_pie['Wins'].apply(lambda x: int(x) if x.is_integer() else x)
plt.pie(wins_for_pie['Wins'], labels=wins_for_pie['Team'], autopct='%1.1f%%', startangle=90)
plt.title('Win Distribution Among Teams', fontsize=16, fontweight='bold')
plt.axis('equal')
plt.tight_layout()
plt.savefig('2_win_distribution.png', dpi=300, bbox_inches='tight')
plt.show()

# Visualization 3: Wins vs Losses (Grouped Bar Chart)
plt.figure(figsize=(12, 6))
x = np.arange(len(team_stats_sorted))
width = 0.35
fig, ax = plt.subplots(figsize=(12, 6))
rects1 = ax.bar(x - width/2, team_stats_sorted['Wins'], width, label='Wins', color='#2E86AB')
rects2 = ax.bar(x + width/2, team_stats_sorted['Losses'], width, label='Losses', color='#A23B72')
ax.set_xlabel('Teams')
ax.set_ylabel('Number of Matches')
ax.set_title('Wins vs Losses by Team')
ax.set_xticks(x)
ax.set_xticklabels(team_stats_sorted['Team'], rotation=45, ha='right')
ax.legend()
plt.tight_layout()
plt.savefig('3_wins_vs_losses.png', dpi=300, bbox_inches='tight')
plt.show()

# 2. BATTING ANALYSIS - SIXES AND FOURS
print("\n2. BATTING ANALYSIS - SIXES AND FOURS")
print("-" * 40)

# Get team boundary stats
team_boundary_stats = {}
for idx, row in df.iterrows():
    for team_type in ['Team1', 'Team2']:
        team = row[team_type]
        fours = row.get(f'{team_type}_Fours', 0)
        sixes = row.get(f'{team_type}_Sixes', 0)

        if team not in team_boundary_stats:
            team_boundary_stats[team] = {'total_fours': 0, 'total_sixes': 0, 'total_matches': 0}

        team_boundary_stats[team]['total_fours'] += int(fours) if pd.notna(fours) else 0
        team_boundary_stats[team]['total_sixes'] += int(sixes) if pd.notna(sixes) else 0
        team_boundary_stats[team]['total_matches'] += 1

# Create boundary stats DataFrame
boundary_df = pd.DataFrame([
    {'Team': team,
     'Total_Fours': stats['total_fours'],
     'Total_Sixes': stats['total_sixes'],
     'Average_Fours': stats['total_fours']/stats['total_matches'],
     'Average_Sixes': stats['total_sixes']/stats['total_matches']}
    for team, stats in team_boundary_stats.items()
])

# Visualization 4: Total Sixes by Team (Horizontal Bar Chart)
plt.figure(figsize=(12, 6))
boundary_df_sorted = boundary_df.sort_values('Total_Sixes', ascending=True)
bars = plt.barh(boundary_df_sorted['Team'], boundary_df_sorted['Total_Sixes'], color='#F18F01')
plt.title('Total Sixes Hit by Each Team', fontsize=16, fontweight='bold')
plt.xlabel('Number of Sixes', fontsize=12)
plt.ylabel('Teams', fontsize=12)
# Add value labels on bars
for bar in bars:
    width = bar.get_width()
    plt.text(width + 0.5, bar.get_y() + bar.get_height()/2,
             f'{int(width)}', ha='left', va='center')
plt.tight_layout()
plt.savefig('4_total_sixes_by_team.png', dpi=300, bbox_inches='tight')
plt.show()

# Visualization 5: Total Fours by Team (Stacked Bar Chart)
plt.figure(figsize=(12, 6))
boundary_df_sorted_fours = boundary_df.sort_values('Total_Fours', ascending=False)
bottom = np.zeros(len(boundary_df_sorted_fours))
colors = ['#2E86AB', '#A23B72']
plt.bar(boundary_df_sorted_fours['Team'], boundary_df_sorted_fours['Total_Fours'],
        label='Fours', color=colors[0])
plt.bar(boundary_df_sorted_fours['Team'], boundary_df_sorted_fours['Total_Sixes'],
        bottom=boundary_df_sorted_fours['Total_Fours'], label='Sixes', color=colors[1])
plt.title('Total Boundaries by Team', fontsize=16, fontweight='bold')
plt.xlabel('Teams', fontsize=12)
plt.ylabel('Number of Boundaries', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.legend()
plt.tight_layout()
plt.savefig('5_total_boundaries_by_team.png', dpi=300, bbox_inches='tight')
plt.show()

# Visualization 6: Fours vs Sixes Ratio (Scatter Plot)
plt.figure(figsize=(10, 8))
plt.scatter(boundary_df['Total_Fours'], boundary_df['Total_Sixes'],
            s=100, alpha=0.7, color='#2E86AB', edgecolors='black')
plt.title('Fours vs Sixes Relationship by Team', fontsize=16, fontweight='bold')
plt.xlabel('Total Fours', fontsize=12)
plt.ylabel('Total Sixes', fontsize=12)

# Add team labels
for i, row in boundary_df.iterrows():
    plt.annotate(row['Team'], (row['Total_Fours'] + 1, row['Total_Sixes'] + 0.5),
                 fontsize=9, alpha=0.8)

# Add trendline
z = np.polyfit(boundary_df['Total_Fours'], boundary_df['Total_Sixes'], 1)
p = np.poly1d(z)
plt.plot(boundary_df['Total_Fours'], p(boundary_df['Total_Fours']),
         "r--", alpha=0.5, label='Trendline')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('6_fours_vs_sixes_scatter.png', dpi=300, bbox_inches='tight')
plt.show()

# 3. BOWLING ANALYSIS - WICKETS
print("\n3. BOWLING ANALYSIS - WICKETS")
print("-" * 40)

# Calculate wickets taken by each team
team_wicket_stats = {}
for idx, row in df.iterrows():
    for team_type in ['Team1', 'Team2']:
        team = row[team_type]
        wickets_lost = row.get(f'{team_type}_Wickets', 0)

        # Wickets taken = 10 - wickets lost by opposition
        # First find the opposition
        if team_type == 'Team1':
            opposition = row['Team2']
            opposition_wickets = row.get('Team2_Wickets', 0)
        else:
            opposition = row['Team1']
            opposition_wickets = row.get('Team1_Wickets', 0)

        wickets_taken = 10 - opposition_wickets if opposition_wickets <= 10 else 0

        if team not in team_wicket_stats:
            team_wicket_stats[team] = {'total_wickets': 0, 'matches': 0}

        team_wicket_stats[team]['total_wickets'] += wickets_taken
        team_wicket_stats[team]['matches'] += 1

# Create wickets DataFrame
wicket_df = pd.DataFrame([
    {'Team': team,
     'Total_Wickets': stats['total_wickets'],
     'Average_Wickets': stats['total_wickets']/stats['matches']}
    for team, stats in team_wicket_stats.items()
])

# Visualization 7: Wickets Taken by Team (Bar Chart with Gradient)
plt.figure(figsize=(12, 6))
wicket_df_sorted = wicket_df.sort_values('Total_Wickets', ascending=True)
colors = plt.cm.YlOrRd(np.linspace(0.4, 1, len(wicket_df_sorted)))
bars = plt.barh(wicket_df_sorted['Team'], wicket_df_sorted['Total_Wickets'], color=colors)
plt.title('Total Wickets Taken by Each Team', fontsize=16, fontweight='bold')
plt.xlabel('Number of Wickets', fontsize=12)
plt.ylabel('Teams', fontsize=12)
# Add value labels on bars
for bar in bars:
    width = bar.get_width()
    plt.text(width + 0.5, bar.get_y() + bar.get_height()/2,
             f'{int(width)}', ha='left', va='center')
plt.tight_layout()
plt.savefig('7_wickets_by_team.png', dpi=300, bbox_inches='tight')
plt.show()

# 4. INDIVIDUAL PLAYER ANALYSIS
print("\n4. INDIVIDUAL PLAYER ANALYSIS")
print("-" * 40)

# Extract Player of the Match data
player_of_match_counts = df['Player_of_the_Match'].value_counts().head(10)

# Visualization 8: Top Player of the Match Winners (Horizontal Bar)
plt.figure(figsize=(12, 6))
player_of_match_counts_sorted = player_of_match_counts.sort_values(ascending=True)
bars = plt.barh(player_of_match_counts_sorted.index, player_of_match_counts_sorted.values,
                color=plt.cm.Set2(np.arange(len(player_of_match_counts_sorted))))
plt.title('Top 10 Player of the Match Winners', fontsize=16, fontweight='bold')
plt.xlabel('Number of Awards', fontsize=12)
plt.ylabel('Players', fontsize=12)
# Add value labels on bars
for bar in bars:
    width = bar.get_width()
    plt.text(width + 0.1, bar.get_y() + bar.get_height()/2,
             f'{int(width)}', ha='left', va='center')
plt.tight_layout()
plt.savefig('8_top_player_of_match.png', dpi=300, bbox_inches='tight')
plt.show()

# 5. SCORING ANALYSIS
print("\n5. SCORING ANALYSIS")
print("-" * 40)

# Calculate total runs by team
team_runs_stats = {}
for idx, row in df.iterrows():
    for team_type in ['Team1', 'Team2']:
        team = row[team_type]
        runs = row.get(f'{team_type}_Total_Runs', 0)

        if team not in team_runs_stats:
            team_runs_stats[team] = {'total_runs': 0, 'matches': 0, 'highest_score': 0}

        team_runs_stats[team]['total_runs'] += int(runs) if pd.notna(runs) else 0
        team_runs_stats[team]['matches'] += 1
        current_runs = int(runs) if pd.notna(runs) else 0
        if current_runs > team_runs_stats[team]['highest_score']:
            team_runs_stats[team]['highest_score'] = current_runs

# Create runs DataFrame
runs_df = pd.DataFrame([
    {'Team': team,
     'Total_Runs': stats['total_runs'],
     'Average_Runs': stats['total_runs']/stats['matches'],
     'Highest_Score': stats['highest_score']}
    for team, stats in team_runs_stats.items()
])

# Visualization 9: Total Runs by Team (Bar Chart)
plt.figure(figsize=(12, 6))
runs_df_sorted = runs_df.sort_values('Total_Runs', ascending=True)
bars = plt.barh(runs_df_sorted['Team'], runs_df_sorted['Total_Runs'], color='#3D5A80')
plt.title('Total Runs Scored by Each Team', fontsize=16, fontweight='bold')
plt.xlabel('Total Runs', fontsize=12)
plt.ylabel('Teams', fontsize=12)
# Add value labels on bars
for bar in bars:
    width = bar.get_width()
    plt.text(width + 5, bar.get_y() + bar.get_height()/2,
             f'{int(width)}', ha='left', va='center')
plt.tight_layout()
plt.savefig('9_total_runs_by_team.png', dpi=300, bbox_inches='tight')
plt.show()

# Visualization 10: Highest Score by Team (Bar Chart)
plt.figure(figsize=(12, 6))
runs_df_highest = runs_df.sort_values('Highest_Score', ascending=True)
bars = plt.barh(runs_df_highest['Team'], runs_df_highest['Highest_Score'], color='#98C1D9')
plt.title('Highest Score Achieved by Each Team', fontsize=16, fontweight='bold')
plt.xlabel('Runs', fontsize=12)
plt.ylabel('Teams', fontsize=12)
# Add value labels on bars
for bar in bars:
    width = bar.get_width()
    plt.text(width + 2, bar.get_y() + bar.get_height()/2,
             f'{int(width)}', ha='left', va='center')
plt.tight_layout()
plt.savefig('10_highest_score_by_team.png', dpi=300, bbox_inches='tight')
plt.show()

# 6. MATCH OUTCOME ANALYSIS
print("\n6. MATCH OUTCOME ANALYSIS")
print("-" * 40)

# Visualization 11: Win Type Distribution (Pie Chart)
plt.figure(figsize=(10, 8))
win_type_counts = df['Win_Type'].value_counts()
explode = [0.05] * len(win_type_counts)
colors = ['#2E86AB', '#A23B72', '#F18F01', '#73AB84', '#6A0572']
plt.pie(win_type_counts.values, labels=win_type_counts.index,
        autopct='%1.1f%%', startangle=90, explode=explode[:len(win_type_counts)],
        colors=colors[:len(win_type_counts)])
plt.title('Distribution of Win Types', fontsize=16, fontweight='bold')
plt.axis('equal')
plt.tight_layout()
plt.savefig('11_win_type_distribution.png', dpi=300, bbox_inches='tight')
plt.show()

# Visualization 12: Win Margin Distribution (Histogram)
plt.figure(figsize=(12, 6))
win_margin_data = df['Win_Margin_Value'].dropna()
if len(win_margin_data) > 0:
    plt.hist(win_margin_data, bins=15, color='#2E86AB', edgecolor='black', alpha=0.7)
    plt.title('Distribution of Win Margins', fontsize=16, fontweight='bold')
    plt.xlabel('Win Margin', fontsize=12)
    plt.ylabel('Frequency', fontsize=12)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig('12_win_margin_distribution.png', dpi=300, bbox_inches='tight')
    plt.show()

# 7. TOSS ANALYSIS
print("\n7. TOSS ANALYSIS")
print("-" * 40)

# Calculate toss decision impact
toss_decision_counts = df['Toss_Decision'].value_counts()
toss_winner_match_winner = 0
for idx, row in df.iterrows():
    toss_winner = row['Toss_Winner']
    result = row['Result'].lower()

    if 'won' in result:
        # Extract winner
        winner_text = row['Result'].split(' won')[0].strip()
        if winner_text == toss_winner:
            toss_winner_match_winner += 1

# Visualization 13: Toss Decision Distribution (Donut Chart)
plt.figure(figsize=(10, 8))
colors = ['#4ECDC4', '#FF6B6B']
plt.pie(toss_decision_counts.values, labels=toss_decision_counts.index,
        autopct='%1.1f%%', startangle=90, colors=colors, wedgeprops=dict(width=0.3))
plt.title('Toss Decision Distribution', fontsize=16, fontweight='bold')
plt.axis('equal')
center_circle = plt.Circle((0,0),0.70,fc='white')
fig = plt.gcf()
fig.gca().add_artist(center_circle)
plt.tight_layout()
plt.savefig('13_toss_decision_donut.png', dpi=300, bbox_inches='tight')
plt.show()

# Visualization 14: Toss Winner vs Match Winner (Bar Chart)
plt.figure(figsize=(8, 6))
categories = ['Toss Winner Won', 'Toss Winner Lost']
values = [toss_winner_match_winner, len(df) - toss_winner_match_winner]
colors = ['#2E86AB', '#A23B72']
bars = plt.bar(categories, values, color=colors)
plt.title('Impact of Winning the Toss', fontsize=16, fontweight='bold')
plt.ylabel('Number of Matches', fontsize=12)
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height + 0.1,
             f'{int(height)}', ha='center', va='bottom')
plt.tight_layout()
plt.savefig('14_toss_impact.png', dpi=300, bbox_inches='tight')
plt.show()

# 8. VENUE ANALYSIS
print("\n8. VENUE ANALYSIS")
print("-" * 40)

# Visualization 15: Matches by Venue (Bar Chart)
plt.figure(figsize=(12, 6))
venue_counts = df['Venue'].value_counts()
bars = plt.bar(venue_counts.index, venue_counts.values, color=plt.cm.Paired(np.arange(len(venue_counts))))
plt.title('Number of Matches at Each Venue', fontsize=16, fontweight='bold')
plt.xlabel('Venue', fontsize=12)
plt.ylabel('Number of Matches', fontsize=12)
plt.xticks(rotation=45, ha='right')
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height + 0.1,
             f'{int(height)}', ha='center', va='bottom')
plt.tight_layout()
plt.savefig('15_matches_by_venue.png', dpi=300, bbox_inches='tight')
plt.show()

# 9. TIME AND DAY ANALYSIS
print("\n9. TIME AND DAY ANALYSIS")
print("-" * 40)

# Visualization 16: Matches by Day of Week (Bar Chart)
plt.figure(figsize=(10, 6))
day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
day_counts = df['Day_of_Week'].value_counts()
day_counts = day_counts.reindex(day_order)
bars = plt.bar(day_counts.index, day_counts.values, color='#6A0572')
plt.title('Matches Played by Day of Week', fontsize=16, fontweight='bold')
plt.xlabel('Day of Week', fontsize=12)
plt.ylabel('Number of Matches', fontsize=12)
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height + 0.1,
             f'{int(height)}', ha='center', va='bottom')
plt.tight_layout()
plt.savefig('16_matches_by_day.png', dpi=300, bbox_inches='tight')
plt.show()

# 10. TOURNAMENT STAGE ANALYSIS
print("\n10. TOURNAMENT STAGE ANALYSIS")
print("-" * 40)

# Visualization 17: Matches by Tournament Stage (Pie Chart)
plt.figure(figsize=(10, 8))
stage_counts = df['Tournament_Stage'].value_counts()
explode = [0.1 if i == 0 else 0 for i in range(len(stage_counts))]
colors = ['#FF9F1C', '#2EC4B6', '#E71D36', '#FF9F1C']
plt.pie(stage_counts.values, labels=stage_counts.index, autopct='%1.1f%%',
        startangle=90, explode=explode, colors=colors[:len(stage_counts)])
plt.title('Matches by Tournament Stage', fontsize=16, fontweight='bold')
plt.axis('equal')
plt.tight_layout()
plt.savefig('17_matches_by_stage.png', dpi=300, bbox_inches='tight')
plt.show()

# 11. BOUNDARY ANALYSIS OVER TIME
print("\n11. BOUNDARY ANALYSIS OVER TIME")
print("-" * 40)

# Calculate boundaries per match over time
df['Boundaries_per_Match'] = df['Total_Boundaries']

# Visualization 18: Boundaries Trend Over Tournament (Line Chart)
plt.figure(figsize=(14, 6))
plt.plot(df['Match_Sequence'], df['Boundaries_per_Match'],
         marker='o', linestyle='-', color='#2E86AB', linewidth=2, markersize=6)
plt.title('Boundaries Hit per Match Throughout the Tournament', fontsize=16, fontweight='bold')
plt.xlabel('Match Sequence', fontsize=12)
plt.ylabel('Number of Boundaries', fontsize=12)
plt.grid(True, alpha=0.3)
avg_boundaries = df['Boundaries_per_Match'].mean()
plt.axhline(y=avg_boundaries, color='#A23B72', linestyle='--', alpha=0.7,
            label=f'Average: {avg_boundaries:.1f}')
plt.legend()
plt.tight_layout()
plt.savefig('18_boundaries_trend.png', dpi=300, bbox_inches='tight')
plt.show()

# 12. COMPREHENSIVE TEAM COMPARISON
print("\n12. COMPREHENSIVE TEAM COMPARISON")
print("-" * 40)

# Create a comprehensive team stats DataFrame
comprehensive_stats = pd.DataFrame({
    'Team': team_stats['Team'],
    'Matches': team_stats['Matches'],
    'Wins': team_stats['Wins'],
    'Win_Percentage': team_stats['Win_Percentage'],
    'Total_Runs': runs_df['Total_Runs'],
    'Total_Fours': boundary_df['Total_Fours'],
    'Total_Sixes': boundary_df['Total_Sixes'],
    'Total_Wickets': wicket_df['Total_Wickets']
})

# Visualization 19: Team Performance Heatmap
plt.figure(figsize=(12, 8))
numeric_cols = ['Wins', 'Win_Percentage', 'Total_Runs', 'Total_Fours', 'Total_Sixes', 'Total_Wickets']
heatmap_data = comprehensive_stats.set_index('Team')[numeric_cols]
normalized_data = (heatmap_data - heatmap_data.min()) / (heatmap_data.max() - heatmap_data.min())

sns.heatmap(normalized_data, annot=heatmap_data, fmt='.0f', cmap='YlOrRd',
            linewidths=0.5, linecolor='gray', cbar_kws={'label': 'Normalized Scale'})
plt.title('Team Performance Heatmap', fontsize=16, fontweight='bold')
plt.xlabel('Performance Metrics', fontsize=12)
plt.ylabel('Teams', fontsize=12)
plt.tight_layout()
plt.savefig('19_team_performance_heatmap.png', dpi=300, bbox_inches='tight')
plt.show()

# Visualization 20: Top Performers Comparison (Grouped Bar Chart)
plt.figure(figsize=(14, 8))
top_teams = comprehensive_stats.nlargest(5, 'Wins')['Team'].tolist()
top_data = comprehensive_stats[comprehensive_stats['Team'].isin(top_teams)].set_index('Team')

# Select metrics to compare
metrics = ['Total_Runs', 'Total_Fours', 'Total_Sixes', 'Total_Wickets']
x = np.arange(len(top_teams))
width = 0.2

fig, ax = plt.subplots(figsize=(14, 8))
colors = ['#2E86AB', '#A23B72', '#F18F01', '#73AB84']

for i, (metric, color) in enumerate(zip(metrics, colors)):
    values = top_data[metric].values
    offset = (i - len(metrics)/2 + 0.5) * width
    bars = ax.bar(x + offset, values, width, label=metric, color=color, alpha=0.8)

    # Add value labels
    for bar, value in zip(bars, values):
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height + (height * 0.01),
                f'{int(value)}', ha='center', va='bottom', fontsize=9)

ax.set_xlabel('Teams')
ax.set_ylabel('Performance Metrics')
ax.set_title('Top 5 Teams: Performance Comparison', fontsize=16, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(top_teams)
ax.legend()
plt.tight_layout()
plt.savefig('20_top_teams_comparison.png', dpi=300, bbox_inches='tight')
plt.show()

# 13. FINAL MATCH ANALYSIS
print("\n13. FINAL MATCH ANALYSIS")
print("-" * 40)

# Get final match details
final_match = df[df['Tournament_Stage'] == 'Final']
if not final_match.empty:
    final_match = final_match.iloc[0]

    # Visualization 21: Final Match Score Comparison (Grouped Bar Chart)
    plt.figure(figsize=(10, 6))
    teams = [final_match['Team1'], final_match['Team2']]
    scores = [final_match['Team1_Total_Runs'], final_match['Team2_Total_Runs']]
    wickets = [final_match['Team1_Wickets'], final_match['Team2_Wickets']]

    x = np.arange(len(teams))
    width = 0.35

    fig, ax1 = plt.subplots(figsize=(10, 6))
    bars1 = ax1.bar(x - width/2, scores, width, label='Runs', color='#2E86AB', alpha=0.8)
    ax1.set_xlabel('Teams')
    ax1.set_ylabel('Runs Scored', color='#2E86AB')
    ax1.tick_params(axis='y', labelcolor='#2E86AB')
    ax1.set_xticks(x)
    ax1.set_xticklabels(teams)

    ax2 = ax1.twinx()
    bars2 = ax2.bar(x + width/2, wickets, width, label='Wickets Lost', color='#A23B72', alpha=0.8)
    ax2.set_ylabel('Wickets Lost', color='#A23B72')
    ax2.tick_params(axis='y', labelcolor='#A23B72')

    plt.title(f'Final Match: {final_match["Team1"]} vs {final_match["Team2"]}', fontsize=16, fontweight='bold')

    # Add value labels
    for bars, values in zip([bars1, bars2], [scores, wickets]):
        for bar, value in zip(bars, values):
            height = bar.get_height()
            ax = bar.axes
            ax.text(bar.get_x() + bar.get_width()/2., height + 1,
                    f'{int(value)}', ha='center', va='bottom')

    fig.tight_layout()
    plt.savefig('21_final_match_comparison.png', dpi=300, bbox_inches='tight')
    plt.show()

# 14. PLAYER SPECIFIC ANALYSIS
print("\n14. PLAYER SPECIFIC ANALYSIS")
print("-" * 40)

# Analyze top scorers from player columns
# Note: This requires parsing the player statistics columns which have complex formatting
# For now, let's extract from available columns

# Visualization 22: Player of Match Awards Distribution
plt.figure(figsize=(12, 6))
top_players = player_of_match_counts.head(8)
bars = plt.bar(range(len(top_players)), top_players.values,
               color=plt.cm.tab20c(np.arange(len(top_players))))
plt.title('Top Player of Match Awards', fontsize=16, fontweight='bold')
plt.xlabel('Players', fontsize=12)
plt.ylabel('Number of Awards', fontsize=12)
plt.xticks(range(len(top_players)), top_players.index, rotation=45, ha='right')
for bar, value in zip(bars, top_players.values):
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height + 0.1,
             f'{int(value)}', ha='center', va='bottom')
plt.tight_layout()
plt.savefig('22_top_player_awards.png', dpi=300, bbox_inches='tight')
plt.show()

print("\n" + "=" * 80)
print("VISUALIZATION SUMMARY")
print("=" * 80)
print(f"""
Generated {22} different visualizations covering:

1.  Team Wins Analysis
2.  Win Distribution
3.  Wins vs Losses
4.  Sixes by Team
5.  Boundaries by Team
6.  Fours vs Sixes Relationship
7.  Wickets by Team
8.  Player of the Match Awards
9.  Runs by Team
10. Highest Scores by Team
11. Win Type Distribution
12. Win Margin Distribution
13. Toss Decision Analysis
14. Toss Impact Analysis
15. Venue Distribution
16. Day-wise Match Distribution
17. Tournament Stage Distribution
18. Boundaries Trend Over Time
19. Team Performance Heatmap
20. Top Teams Performance Comparison
21. Final Match Analysis
22. Player Awards Distribution

All visualizations have been saved as PNG files (1-22) in the current directory.
""")

# Create summary statistics
print("\n" + "=" * 80)
print("KEY STATISTICS SUMMARY")
print("=" * 80)

# Find top performers
top_winning_team = team_stats.loc[team_stats['Wins'].idxmax()]
top_boundary_team = boundary_df.loc[boundary_df['Total_Sixes'].idxmax()]
top_wicket_team = wicket_df.loc[wicket_df['Total_Wickets'].idxmax()]
top_scoring_team = runs_df.loc[runs_df['Total_Runs'].idxmax()]

print(f"""
TOP PERFORMERS:

1. Most Wins: {top_winning_team['Team']} ({top_winning_team['Wins']} wins, {top_winning_team['Win_Percentage']}% win rate)
2. Most Sixes: {top_boundary_team['Team']} ({top_boundary_team['Total_Sixes']} sixes)
3. Most Wickets: {top_wicket_team['Team']} ({top_wicket_team['Total_Wickets']} wickets)
4. Most Runs: {top_scoring_team['Team']} ({top_scoring_team['Total_Runs']} runs)
5. Most Player of Match Awards: {player_of_match_counts.index[0]} ({player_of_match_counts.iloc[0]} awards)

TOURNAMENT OVERVIEW:
- Total Matches: {len(df)}
- Teams Participated: {len(all_teams)}
- Average Score: {df['Team1_Total_Runs'].mean():.1f} runs
- Average Boundaries per Match: {df['Total_Boundaries'].mean():.1f}
- Most Common Win Type: {win_type_counts.index[0]} ({win_type_counts.iloc[0]} matches)
- Toss Winner Won: {toss_winner_match_winner} matches ({(toss_winner_match_winner/len(df)*100):.1f}%)
""")

# Save comprehensive statistics to CSV
comprehensive_stats.to_csv('asia_cup_2025_comprehensive_stats.csv', index=False)
print(f"\nComprehensive statistics saved to 'asia_cup_2025_comprehensive_stats.csv'")

print("\n" + "=" * 80)
print("ANALYSIS COMPLETED SUCCESSFULLY!")
print("=" * 80)