# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WWwVbmcycCEN6-2MMsTdrpXMwD2HFxti
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta

def create_tri_series_dataset():
    # Create empty DataFrame with specified columns
    columns = [
        'Match_Number', 'Series', 'Date', 'Day', 'Time', 'Venue', 'Team1', 'Team2',
        'Toss_Winner', 'Toss_Decision', 'Result', 'Player_of_the_Match', 'Umpires',
        'Third_Umpire', 'Match_Referee', 'Team1_Score', 'Team1_Total_Runs',
        'Team1_Wickets', 'Team1_Overs', 'Team1_Extras', 'Team1_Byes', 'Team1_Leg_Byes',
        'Team1_Wides', 'Team1_No_Balls', 'Team1_Powerplay_Runs', 'Team1_Powerplay_Overs',
        'Team1_Top_Scorer', 'Team1_Top_Wicket_Taker', 'Team1_Fours', 'Team1_Sixes',
        'Team1_Playing_XI', 'Team1_Coach', 'Team2_Score', 'Team2_Total_Runs',
        'Team2_Wickets', 'Team2_Overs', 'Team2_Extras', 'Team2_Byes', 'Team2_Leg_Byes',
        'Team2_Wides', 'Team2_No_Balls', 'Team2_Powerplay_Runs', 'Team2_Powerplay_Overs',
        'Team2_Top_Scorer', 'Team2_Top_Wicket_Taker', 'Team2_Fours', 'Team2_Sixes',
        'Team2_Playing_XI', 'Team2_Coach'
    ]

    df = pd.DataFrame(columns=columns)

    # Define teams and their details
    teams = {
        'Pakistan': {
            'coach': 'Mike Hesson',
            'players_m1': ['Sahibzada Farhan', 'Saim Ayub', 'Babar Azam', 'Salman Agha',
                          'Usman Khan', 'Fakhar Zaman', 'Mohammad Nawaz', 'Faheem Ashraf',
                          'Shaheen Afridi', 'Salman Mirza', 'Abrar Ahmed'],
            'players_m3': ['Saim Ayub', 'Sahibzada Farhan', 'Babar Azam', 'Salman Agha',
                          'Fakhar Zaman', 'Usman Khan', 'Mohammad Nawaz', 'Faheem Ashraf',
                          'Mohammad Wasim Jr', 'Salman Mirza', 'Abrar Ahmed'],
            'players_m4': ['Sahibzada Farhan', 'Saim Ayub', 'Babar Azam', 'Salman Agha',
                          'Usman Khan', 'Fakhar Zaman', 'Mohammad Nawaz', 'Faheem Ashraf',
                          'Mohammad Wasim Jr', 'Naseem Shah', 'Usman Tariq'],
            'players_m6': ['Sahibzada Farhan', 'Saim Ayub', 'Babar Azam', 'Salman Agha',
                          'Usman Khan', 'Fakhar Zaman', 'Mohammad Nawaz', 'Faheem Ashraf',
                          'Mohammad Wasim Jr', 'Salman Mirza', 'Abrar Ahmed'],
            'players_m7': ['Sahibzada Farhan', 'Saim Ayub', 'Babar Azam', 'Salman Agha',
                          'Fakhar Zaman', 'Usman Khan', 'Mohammad Nawaz', 'Faheem Ashraf',
                          'Shaheen Afridi', 'Salman Mirza', 'Abrar Ahmed']
        },
        'Zimbabwe': {
            'coach': 'Justin Sammons',
            'players_m1': ['Brian Bennett', 'T Marumani', 'Brendan Taylor', 'Ryan Burl',
                          'Sikandar Raza', 'Tony Munyonga', 'Brad Evans', 'Tashinga Musekiwa',
                          'Graeme Cremer', 'Tinotenda Maposa', 'Richard Ngarava'],
            'players_m2': ['Brian Bennett', 'T Marumani', 'Brendan Taylor', 'Ryan Burl',
                          'Sikandar Raza', 'Tony Munyonga', 'Tashinga Musekiwa', 'Brad Evans',
                          'Tinotenda Maposa', 'Richard Ngarava', 'Graeme Cremer'],
            'players_m4': ['Brian Bennett', 'T Marumani', 'Brendan Taylor', 'Sikandar Raza',
                          'Ryan Burl', 'Tony Munyonga', 'Tashinga Musekiwa', 'Brad Evans',
                          'Tinotenda Maposa', 'Richard Ngarava', 'Wellington Masakadza'],
            'players_m5': ['Brian Bennett', 'T Marumani', 'Dion Myers', 'Brendan Taylor',
                          'Sikandar Raza', 'Ryan Burl', 'Tashinga Musekiwa', 'Wellington Masakadza',
                          'Brad Evans', 'Tinotenda Maposa', 'Richard Ngarava']
        },
        'Sri Lanka': {
            'coach': 'Sanath Jayasuriya',
            'players_m2': ['Pathum Nissanka', 'Kusal Mendis', 'Kusal Perera', 'Bhanuka Rajapaksa',
                          'Dasun Shanaka', 'Kamindu Mendis', 'Wanindu Hasaranga', 'Dushmantha Chameera',
                          'Maheesh Theekshana', 'Nuwan Thushara', 'Eshan Malinga'],
            'players_m3': ['Pathum Nissanka', 'Kusal Mendis', 'Kamil Mishara', 'Kusal Perera',
                          'Dasun Shanaka', 'Janith Liyanage', 'Kamindu Mendis', 'Wanindu Hasaranga',
                          'Dushmantha Chameera', 'Eshan Malinga', 'Vijayakanth Viyaskanth'],
            'players_m5': ['Pathum Nissanka', 'Kamil Mishara', 'Kusal Mendis', 'Kusal Perera',
                          'Janith Liyanage', 'Dasun Shanaka', 'Pavan Rathnayake', 'Wanindu Hasaranga',
                          'Dushmantha Chameera', 'Maheesh Theekshana', 'Eshan Malinga'],
            'players_m6': ['Pathum Nissanka', 'Kamil Mishara', 'Kusal Mendis', 'Kusal Perera',
                          'Janith Liyanage', 'Dasun Shanaka', 'Pavan Rathnayake', 'Wanindu Hasaranga',
                          'Dushmantha Chameera', 'Maheesh Theekshana', 'Eshan Malinga'],
            'players_m7': ['Pathum Nissanka', 'Kamil Mishara', 'Kusal Mendis', 'Kusal Perera',
                          'Janith Liyanage', 'Dasun Shanaka', 'Pavan Rathnayake', 'Wanindu Hasaranga',
                          'Dushmantha Chameera', 'Maheesh Theekshana', 'Eshan Malinga']
        }
    }

    # Define venue
    venue = 'Rawalpindi Cricket Stadium, Rawalpindi'

    # Match 1: Pakistan vs Zimbabwe
    match_date_1 = datetime(2025, 11, 18)
    match1 = {
        'Match_Number': 1,
        'Series': 'Pakistan T20I Tri-Series 2025',
        'Date': match_date_1.strftime('%Y-%m-%d'),
        'Day': 'Tuesday',
        'Time': '6:00 PM LOCAL',
        'Venue': venue,
        'Team1': 'Zimbabwe',
        'Team2': 'Pakistan',
        'Toss_Winner': 'Pakistan',
        'Toss_Decision': 'Field',
        'Result': 'Pakistan won by 5 wickets',
        'Player_of_the_Match': 'Mohammad Nawaz',
        'Umpires': 'Asif Yaqoob, Rashid Riaz',
        'Third_Umpire': 'Faisal Afridi',
        'Match_Referee': 'Reon King',
        'Team1_Score': '147-8',
        'Team1_Total_Runs': 147,
        'Team1_Wickets': 8,
        'Team1_Overs': 20,
        'Team1_Extras': 3,
        'Team1_Byes': 0,
        'Team1_Leg_Byes': 0,
        'Team1_Wides': 3,
        'Team1_No_Balls': 0,
        'Team1_Powerplay_Runs': 59,
        'Team1_Powerplay_Overs': 6,
        'Team1_Top_Scorer': 'Brian Bennett 49(36)',
        'Team1_Top_Wicket_Taker': 'Mohammad Nawaz 2/22',
        'Team1_Fours': 17,
        'Team1_Sixes': 2,
        'Team1_Playing_XI': ', '.join(teams['Zimbabwe']['players_m1']),
        'Team1_Coach': teams['Zimbabwe']['coach'],
        'Team2_Score': '151-5',
        'Team2_Total_Runs': 151,
        'Team2_Wickets': 5,
        'Team2_Overs': 19.2,
        'Team2_Extras': 10,
        'Team2_Byes': 2,
        'Team2_Leg_Byes': 3,
        'Team2_Wides': 3,
        'Team2_No_Balls': 2,
        'Team2_Powerplay_Runs': 31,
        'Team2_Powerplay_Overs': 6,
        'Team2_Top_Scorer': 'Fakhar Zaman 44(32)',
        'Team2_Top_Wicket_Taker': 'Brad Evans 2/26',
        'Team2_Fours': 11,
        'Team2_Sixes': 4,
        'Team2_Playing_XI': ', '.join(teams['Pakistan']['players_m1']),
        'Team2_Coach': teams['Pakistan']['coach']
    }

    # Match 2: Sri Lanka vs Zimbabwe
    match_date_2 = datetime(2025, 11, 20)
    match2 = {
        'Match_Number': 2,
        'Series': 'Pakistan T20I Tri-Series 2025',
        'Date': match_date_2.strftime('%Y-%m-%d'),
        'Day': 'Thursday',
        'Time': '6:00 PM LOCAL',
        'Venue': venue,
        'Team1': 'Zimbabwe',
        'Team2': 'Sri Lanka',
        'Toss_Winner': 'Sri Lanka',
        'Toss_Decision': 'Field',
        'Result': 'Zimbabwe won by 67 runs',
        'Player_of_the_Match': 'Sikandar Raza',
        'Umpires': 'Faisal Afridi, Rashid Riaz',
        'Third_Umpire': 'Asif Yaqoob',
        'Match_Referee': 'Reon King',
        'Team1_Score': '162-8',
        'Team1_Total_Runs': 162,
        'Team1_Wickets': 8,
        'Team1_Overs': 20,
        'Team1_Extras': 4,
        'Team1_Byes': 0,
        'Team1_Leg_Byes': 3,
        'Team1_Wides': 0,
        'Team1_No_Balls': 1,
        'Team1_Powerplay_Runs': 43,
        'Team1_Powerplay_Overs': 6,
        'Team1_Top_Scorer': 'Brian Bennett 49(42)',
        'Team1_Top_Wicket_Taker': 'Brad Evans 3/9',
        'Team1_Fours': 10,
        'Team1_Sixes': 4,
        'Team1_Playing_XI': ', '.join(teams['Zimbabwe']['players_m2']),
        'Team1_Coach': teams['Zimbabwe']['coach'],
        'Team2_Score': '95-10',
        'Team2_Total_Runs': 95,
        'Team2_Wickets': 10,
        'Team2_Overs': 20,
        'Team2_Extras': 12,
        'Team2_Byes': 2,
        'Team2_Leg_Byes': 4,
        'Team2_Wides': 6,
        'Team2_No_Balls': 0,
        'Team2_Powerplay_Runs': 25,
        'Team2_Powerplay_Overs': 6,
        'Team2_Top_Scorer': 'Dasun Shanaka 34(25)',
        'Team2_Top_Wicket_Taker': 'Brad Evans 3/9',
        'Team2_Fours': 4,
        'Team2_Sixes': 2,
        'Team2_Playing_XI': ', '.join(teams['Sri Lanka']['players_m2']),
        'Team2_Coach': teams['Sri Lanka']['coach']
    }

    # Match 3: Pakistan vs Sri Lanka
    match_date_3 = datetime(2025, 11, 22)
    match3 = {
        'Match_Number': 3,
        'Series': 'Pakistan T20I Tri-Series 2025',
        'Date': match_date_3.strftime('%Y-%m-%d'),
        'Day': 'Saturday',
        'Time': '6:00 PM LOCAL',
        'Venue': venue,
        'Team1': 'Sri Lanka',
        'Team2': 'Pakistan',
        'Toss_Winner': 'Sri Lanka',
        'Toss_Decision': 'Bat',
        'Result': 'Pakistan won by 7 wickets',
        'Player_of_the_Match': 'Mohammad Nawaz',
        'Umpires': 'Asif Yaqoob, Faisal Afridi',
        'Third_Umpire': 'Rashid Riaz',
        'Match_Referee': 'Reon King',
        'Team1_Score': '128-7',
        'Team1_Total_Runs': 128,
        'Team1_Wickets': 7,
        'Team1_Overs': 20,
        'Team1_Extras': 6,
        'Team1_Byes': 1,
        'Team1_Leg_Byes': 0,
        'Team1_Wides': 5,
        'Team1_No_Balls': 0,
        'Team1_Powerplay_Runs': 44,
        'Team1_Powerplay_Overs': 6,
        'Team1_Top_Scorer': 'Janith Liyanage 41(38)',
        'Team1_Top_Wicket_Taker': 'Mohammad Nawaz 3/16',
        'Team1_Fours': 7,
        'Team1_Sixes': 4,
        'Team1_Playing_XI': ', '.join(teams['Sri Lanka']['players_m3']),
        'Team1_Coach': teams['Sri Lanka']['coach'],
        'Team2_Score': '131-3',
        'Team2_Total_Runs': 131,
        'Team2_Wickets': 3,
        'Team2_Overs': 15.3,
        'Team2_Extras': 10,
        'Team2_Byes': 0,
        'Team2_Leg_Byes': 4,
        'Team2_Wides': 6,
        'Team2_No_Balls': 0,
        'Team2_Powerplay_Runs': 53,
        'Team2_Powerplay_Overs': 6,
        'Team2_Top_Scorer': 'Sahibzada Farhan 80(45)',
        'Team2_Top_Wicket_Taker': 'Dushmantha Chameera 2/29',
        'Team2_Fours': 10,
        'Team2_Sixes': 6,
        'Team2_Playing_XI': ', '.join(teams['Pakistan']['players_m3']),
        'Team2_Coach': teams['Pakistan']['coach']
    }

    # Match 4: Pakistan vs Zimbabwe
    match_date_4 = datetime(2025, 11, 23)
    match4 = {
        'Match_Number': 4,
        'Series': 'Pakistan T20I Tri-Series 2025',
        'Date': match_date_4.strftime('%Y-%m-%d'),
        'Day': 'Sunday',
        'Time': '6:00 PM LOCAL',
        'Venue': venue,
        'Team1': 'Pakistan',
        'Team2': 'Zimbabwe',
        'Toss_Winner': 'Pakistan',
        'Toss_Decision': 'Bat',
        'Result': 'Pakistan won by 69 runs',
        'Player_of_the_Match': 'Usman Tariq',
        'Umpires': 'Faisal Afridi, Rashid Riaz',
        'Third_Umpire': 'Asif Yaqoob',
        'Match_Referee': 'Reon King',
        'Team1_Score': '195-5',
        'Team1_Total_Runs': 195,
        'Team1_Wickets': 5,
        'Team1_Overs': 20,
        'Team1_Extras': 10,
        'Team1_Byes': 0,
        'Team1_Leg_Byes': 5,
        'Team1_Wides': 4,
        'Team1_No_Balls': 1,
        'Team1_Powerplay_Runs': 53,
        'Team1_Powerplay_Overs': 6,
        'Team1_Top_Scorer': 'Babar Azam 74(52)',
        'Team1_Top_Wicket_Taker': 'Usman Tariq 4/18',
        'Team1_Fours': 12,
        'Team1_Sixes': 10,
        'Team1_Playing_XI': ', '.join(teams['Pakistan']['players_m4']),
        'Team1_Coach': teams['Pakistan']['coach'],
        'Team2_Score': '126-10',
        'Team2_Total_Runs': 126,
        'Team2_Wickets': 10,
        'Team2_Overs': 19,
        'Team2_Extras': 4,
        'Team2_Byes': 0,
        'Team2_Leg_Byes': 1,
        'Team2_Wides': 2,
        'Team2_No_Balls': 1,
        'Team2_Powerplay_Runs': 43,
        'Team2_Powerplay_Overs': 6,
        'Team2_Top_Scorer': 'Ryan Burl 67(49)',
        'Team2_Top_Wicket_Taker': 'Usman Tariq 4/18',
        'Team2_Fours': 15,
        'Team2_Sixes': 3,
        'Team2_Playing_XI': ', '.join(teams['Zimbabwe']['players_m4']),
        'Team2_Coach': teams['Zimbabwe']['coach']
    }

    # Match 5: Sri Lanka vs Zimbabwe
    match_date_5 = datetime(2025, 11, 25)
    match5 = {
        'Match_Number': 5,
        'Series': 'Pakistan T20I Tri-Series 2025',
        'Date': match_date_5.strftime('%Y-%m-%d'),
        'Day': 'Tuesday',
        'Time': '6:00 PM LOCAL',
        'Venue': venue,
        'Team1': 'Zimbabwe',
        'Team2': 'Sri Lanka',
        'Toss_Winner': 'Zimbabwe',
        'Toss_Decision': 'Bat',
        'Result': 'Sri Lanka won by 9 wickets',
        'Player_of_the_Match': 'Pathum Nissanka',
        'Umpires': 'Asif Yaqoob, Rashid Riaz',
        'Third_Umpire': 'Ahsan Raza',
        'Match_Referee': 'Reon King',
        'Team1_Score': '146-5',
        'Team1_Total_Runs': 146,
        'Team1_Wickets': 5,
        'Team1_Overs': 20,
        'Team1_Extras': 8,
        'Team1_Byes': 1,
        'Team1_Leg_Byes': 4,
        'Team1_Wides': 2,
        'Team1_No_Balls': 1,
        'Team1_Powerplay_Runs': 44,
        'Team1_Powerplay_Overs': 6,
        'Team1_Top_Scorer': 'Ryan Burl 37(26)',
        'Team1_Top_Wicket_Taker': 'Maheesh Theekshana 2/23',
        'Team1_Fours': 16,
        'Team1_Sixes': 3,
        'Team1_Playing_XI': ', '.join(teams['Zimbabwe']['players_m5']),
        'Team1_Coach': teams['Zimbabwe']['coach'],
        'Team2_Score': '148-1',
        'Team2_Total_Runs': 148,
        'Team2_Wickets': 1,
        'Team2_Overs': 16.2,
        'Team2_Extras': 13,
        'Team2_Byes': 1,
        'Team2_Leg_Byes': 2,
        'Team2_Wides': 10,
        'Team2_No_Balls': 0,
        'Team2_Powerplay_Runs': 64,
        'Team2_Powerplay_Overs': 6,
        'Team2_Top_Scorer': 'Pathum Nissanka 98(58)',
        'Team2_Top_Wicket_Taker': 'Brad Evans 1/36',
        'Team2_Fours': 14,
        'Team2_Sixes': 5,
        'Team2_Playing_XI': ', '.join(teams['Sri Lanka']['players_m5']),
        'Team2_Coach': teams['Sri Lanka']['coach']
    }

    # Match 6: Pakistan vs Sri Lanka
    match_date_6 = datetime(2025, 11, 27)
    match6 = {
        'Match_Number': 6,
        'Series': 'Pakistan T20I Tri-Series 2025',
        'Date': match_date_6.strftime('%Y-%m-%d'),
        'Day': 'Thursday',
        'Time': '6:00 PM LOCAL',
        'Venue': venue,
        'Team1': 'Sri Lanka',
        'Team2': 'Pakistan',
        'Toss_Winner': 'Pakistan',
        'Toss_Decision': 'Field',
        'Result': 'Sri Lanka won by 6 runs',
        'Player_of_the_Match': 'Dushmantha Chameera',
        'Umpires': 'Ahsan Raza, Faisal Afridi',
        'Third_Umpire': 'Rashid Riaz',
        'Match_Referee': 'Reon King',
        'Team1_Score': '184-5',
        'Team1_Total_Runs': 184,
        'Team1_Wickets': 5,
        'Team1_Overs': 20,
        'Team1_Extras': 13,
        'Team1_Byes': 1,
        'Team1_Leg_Byes': 4,
        'Team1_Wides': 8,
        'Team1_No_Balls': 0,
        'Team1_Powerplay_Runs': 58,
        'Team1_Powerplay_Overs': 6,
        'Team1_Top_Scorer': 'Kamil Mishara 76(48)',
        'Team1_Top_Wicket_Taker': 'Dushmantha Chameera 4/20',
        'Team1_Fours': 15,
        'Team1_Sixes': 5,
        'Team1_Playing_XI': ', '.join(teams['Sri Lanka']['players_m6']),
        'Team1_Coach': teams['Sri Lanka']['coach'],
        'Team2_Score': '178-7',
        'Team2_Total_Runs': 178,
        'Team2_Wickets': 7,
        'Team2_Overs': 20,
        'Team2_Extras': 11,
        'Team2_Byes': 2,
        'Team2_Leg_Byes': 1,
        'Team2_Wides': 8,
        'Team2_No_Balls': 0,
        'Team2_Powerplay_Runs': 45,
        'Team2_Powerplay_Overs': 6,
        'Team2_Top_Scorer': 'Salman Agha 63(44)',
        'Team2_Top_Wicket_Taker': 'Dushmantha Chameera 4/20',
        'Team2_Fours': 14,
        'Team2_Sixes': 8,
        'Team2_Playing_XI': ', '.join(teams['Pakistan']['players_m6']),
        'Team2_Coach': teams['Pakistan']['coach']
    }

    # Match 7: FINAL - Pakistan vs Sri Lanka
    match_date_7 = datetime(2025, 11, 29)
    match7 = {
        'Match_Number': 7,
        'Series': 'Pakistan T20I Tri-Series 2025 - FINAL',
        'Date': match_date_7.strftime('%Y-%m-%d'),
        'Day': 'Saturday',
        'Time': '6:00 PM LOCAL',
        'Venue': venue,
        'Team1': 'Sri Lanka',
        'Team2': 'Pakistan',
        'Toss_Winner': 'Pakistan',
        'Toss_Decision': 'Field',
        'Result': 'Pakistan won by 6 wickets',
        'Player_of_the_Match': 'Mohammad Nawaz',
        'Umpires': 'Ahsan Raza, Asif Yaqoob',
        'Third_Umpire': 'Rashid Riaz',
        'Match_Referee': 'Reon King',
        'Team1_Score': '114-10',
        'Team1_Total_Runs': 114,
        'Team1_Wickets': 10,
        'Team1_Overs': 19.1,
        'Team1_Extras': 13,
        'Team1_Byes': 0,
        'Team1_Leg_Byes': 8,
        'Team1_Wides': 5,
        'Team1_No_Balls': 0,
        'Team1_Powerplay_Runs': 56,
        'Team1_Powerplay_Overs': 6,
        'Team1_Top_Scorer': 'Kamil Mishara 59(47)',
        'Team1_Top_Wicket_Taker': 'Mohammad Nawaz 3/17',
        'Team1_Fours': 3,
        'Team1_Sixes': 5,
        'Team1_Playing_XI': ', '.join(teams['Sri Lanka']['players_m7']),
        'Team1_Coach': teams['Sri Lanka']['coach'],
        'Team2_Score': '118-4',
        'Team2_Total_Runs': 118,
        'Team2_Wickets': 4,
        'Team2_Overs': 18.4,
        'Team2_Extras': 2,
        'Team2_Byes': 0,
        'Team2_Leg_Byes': 0,
        'Team2_Wides': 2,
        'Team2_No_Balls': 0,
        'Team2_Powerplay_Runs': 32,
        'Team2_Powerplay_Overs': 6,
        'Team2_Top_Scorer': 'Babar Azam 37(34)',
        'Team2_Top_Wicket_Taker': 'Pavan Rathnayake 2/11',
        'Team2_Fours': 10,
        'Team2_Sixes': 2,
        'Team2_Playing_XI': ', '.join(teams['Pakistan']['players_m7']),
        'Team2_Coach': teams['Pakistan']['coach']
    }

    # Add all matches to dataframe
    matches = [match1, match2, match3, match4, match5, match6, match7]

    for match in matches:
        df = pd.concat([df, pd.DataFrame([match])], ignore_index=True)

    return df

# Create the dataset
dataset = create_tri_series_dataset()

# Save to CSV
csv_filename = 'pakistan_t20i_tri_series_2025_complete.csv'
dataset.to_csv(csv_filename, index=False)

print(f"Complete Tri-Series Dataset created successfully!")
print(f"Saved as '{csv_filename}'")
print(f"\nDataset shape: {dataset.shape}")
print(f"\nTotal matches: {len(dataset)}")
print(f"\nMatch Summary:")
print("=" * 80)
for idx, row in dataset.iterrows():
    print(f"Match {row['Match_Number']}: {row['Team1']} vs {row['Team2']}")
    print(f"  Result: {row['Result']}")
    print(f"  Player of the Match: {row['Player_of_the_Match']}")
    print(f"  Date: {row['Date']}")
    print("-" * 80)

print(f"\nSeries Summary:")
print("=" * 80)
print("Pakistan T20I Tri-Series 2025")
print("Venue: Rawalpindi Cricket Stadium, Rawalpindi")
print("Teams: Pakistan, Sri Lanka, Zimbabwe")
print("Total Matches: 7 (6 group stage + 1 final)")
print("Champion: Pakistan")
print("Player of the Series: Mohammad Nawaz")

import pandas as pd
import matplotlib.pyplot as plt
import os

# Load dataset
df = pd.read_csv("pakistan_t20i_tri_series_2025_complete.csv")

# Create output folder
os.makedirs("figures", exist_ok=True)

most_runs = (
    df.groupby("player_name")["runs"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

most_runs.plot(kind="bar")
plt.title("Most Runs by Player")
plt.ylabel("Runs")
plt.tight_layout()
plt.savefig("figures/most_runs_player.jpg", dpi=300)
plt.close()

df.columns.tolist()

most_runs = (
    df.groupby("batsman")["batsman_runs"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

most_runs.plot(kind="bar")
plt.title("Most Runs by Player")
plt.ylabel("Runs")
plt.tight_layout()
plt.savefig("figures/most_runs_player.jpg", dpi=300)
plt.close()

top_scorer = pd.concat([
    df["Team1_Top_Scorer"],
    df["Team2_Top_Scorer"]
]).value_counts().head(10)

top_scorer.plot(kind="bar")
plt.title("Most Times Top Scorer")
plt.ylabel("Matches")
plt.tight_layout()
plt.savefig("figures/most_top_scorer.jpg", dpi=300)
plt.close()

top_wicket = pd.concat([
    df["Team1_Top_Wicket_Taker"],
    df["Team2_Top_Wicket_Taker"]
]).value_counts().head(10)

top_wicket.plot(kind="bar")
plt.title("Most Times Top Wicket-Taker")
plt.ylabel("Matches")
plt.tight_layout()
plt.savefig("figures/most_top_wicket_taker.jpg", dpi=300)
plt.close()

def extended_analysis(df):
    """Perform extended analysis with more specific queries"""

    print("\n" + "="*60)
    print("EXTENDED ANALYSIS")
    print("="*60)

    # Create analyzer
    analyzer = CricketTriSeriesAnalyzer(df)

    # 1. Match-by-Match Analysis
    print("\n1. MATCH-BY-MATCH DETAILED ANALYSIS:")
    print("-"*60)

    match_details = []
    for idx, match in df.iterrows():
        match_info = {
            'Match': match['Match_Number'],
            'Date': match['Date'],
            'Teams': f"{match['Team1']} vs {match['Team2']}",
            'Toss': f"{match['Toss_Winner']} ({match['Toss_Decision']})",
            'Result': match['Result'],
            'POTM': match['Player_of_the_Match'],
            'Team1_Score': match['Team1_Score'],
            'Team2_Score': match['Team2_Score']
        }
        match_details.append(match_info)

    match_df = pd.DataFrame(match_details)
    print(match_df.to_string(index=False))

    # 2. Close Match Analysis (matches won by less than 20 runs or 2 wickets)
    print("\n\n2. CLOSE MATCHES ANALYSIS:")
    print("-"*60)

    close_matches = []
    for idx, match in df.iterrows():
        result = str(match['Result'])
        if 'won by' in result:
            try:
                margin = int(re.findall(r'\d+', result.split('by')[1])[0])
                if 'wickets' in result and margin <= 3:
                    close_matches.append((match['Match_Number'], result))
                elif 'runs' in result and margin <= 20:
                    close_matches.append((match['Match_Number'], result))
            except:
                pass

    if close_matches:
        for match_num, result in close_matches:
            print(f"Match {match_num}: {result}")
    else:
        print("No close matches found (all were decisive victories)")

    # 3. Individual Match Highs and Lows
    print("\n\n3. INDIVIDUAL MATCH HIGHLIGHTS:")
    print("-"*60)

    # Highest team total
    highest_total = 0
    highest_match = ""
    for idx, match in df.iterrows():
        for team in ['Team1', 'Team2']:
            runs = match[f'{team}_Total_Runs']
            if runs > highest_total:
                highest_total = runs
                highest_match = f"Match {match['Match_Number']}: {match[team]}"

    print(f"Highest Team Total: {highest_total} runs ({highest_match})")

    # Lowest team total
    lowest_total = float('inf')
    lowest_match = ""
    for idx, match in df.iterrows():
        for team in ['Team1', 'Team2']:
            runs = match[f'{team}_Total_Runs']
            if runs < lowest_total:
                lowest_total = runs
                lowest_match = f"Match {match['Match_Number']}: {match[team]}"

    print(f"Lowest Team Total: {lowest_total} runs ({lowest_match})")

    # 4. Powerplay Analysis
    print("\n\n4. POWERPLAY PERFORMANCE ANALYSIS:")
    print("-"*60)

    powerplay_stats = defaultdict(list)
    for idx, match in df.iterrows():
        for team in ['Team1', 'Team2']:
            team_name = match[team]
            pp_runs = match[f'{team}_Powerplay_Runs']
            if pd.notna(pp_runs):
                powerplay_stats[team_name].append(pp_runs)

    for team, scores in powerplay_stats.items():
        avg_pp = np.mean(scores)
        max_pp = max(scores)
        min_pp = min(scores)
        print(f"{team:15} Avg: {avg_pp:.1f}, Max: {max_pp}, Min: {min_pp}")

    # 5. Extras Analysis
    print("\n\n5. EXTRAS ANALYSIS:")
    print("-"*60)

    extras_by_team = defaultdict(lambda: {'total': 0, 'wides': 0, 'noballs': 0})
    for idx, match in df.iterrows():
        for team in ['Team1', 'Team2']:
            team_name = match[team]
            extras = match[f'{team}_Extras']
            wides = match[f'{team}_Wides']
            noballs = match[f'{team}_No_Balls']

            if pd.notna(extras):
                extras_by_team[team_name]['total'] += extras
            if pd.notna(wides):
                extras_by_team[team_name]['wides'] += wides
            if pd.notna(noballs):
                extras_by_team[team_name]['noballs'] += noballs

    for team, data in extras_by_team.items():
        print(f"{team:15} Total Extras: {data['total']}, Wides: {data['wides']}, No Balls: {data['noballs']}")

    # 6. Create Performance Timeline
    create_performance_timeline(df)

    # 7. Head-to-Head Records
    print("\n\n6. HEAD-TO-HEAD RECORDS:")
    print("-"*60)

    h2h = defaultdict(lambda: defaultdict(lambda: {'wins': 0, 'losses': 0}))
    for idx, match in df.iterrows():
        team1 = match['Team1']
        team2 = match['Team2']
        result = str(match['Result'])

        if 'won' in result:
            winner = result.split(' won')[0]
            loser = team2 if winner == team1 else team1

            h2h[winner][loser]['wins'] += 1
            h2h[loser][winner]['losses'] += 1

    teams = list(set(df['Team1'].tolist() + df['Team2'].tolist()))
    for i, team1 in enumerate(teams):
        for j, team2 in enumerate(teams[i+1:], i+1):
            wins_1 = h2h[team1][team2]['wins']
            wins_2 = h2h[team2][team1]['wins']
            if wins_1 > 0 or wins_2 > 0:
                print(f"{team1:15} vs {team2:15}: {wins_1}-{wins_2}")

def create_performance_timeline(df):
    """Create match performance timeline"""
    plt.figure(figsize=(15, 8))

    # Extract match timeline data
    matches = []
    pakistan_scores = []
    srilanka_scores = []
    zimbabwe_scores = []

    for idx, match in df.iterrows():
        match_num = match['Match_Number']
        matches.append(f"M{match_num}")

        # Get scores for each team
        for team in ['Team1', 'Team2']:
            team_name = match[team]
            score = match[f'{team}_Total_Runs']

            if team_name == 'Pakistan':
                pakistan_scores.append(score)
            elif team_name == 'Sri Lanka':
                srilanka_scores.append(score)
            elif team_name == 'Zimbabwe':
                zimbabwe_scores.append(score)

    # Plot timeline
    plt.plot(matches[:len(pakistan_scores)], pakistan_scores, marker='o',
             label='Pakistan', linewidth=2, markersize=8)
    plt.plot(matches[:len(srilanka_scores)], srilanka_scores, marker='s',
             label='Sri Lanka', linewidth=2, markersize=8)
    plt.plot(matches[:len(zimbabwe_scores)], zimbabwe_scores, marker='^',
             label='Zimbabwe', linewidth=2, markersize=8)

    plt.title('Team Performance Timeline - Runs Scored per Match',
              fontsize=16, fontweight='bold')
    plt.xlabel('Match Number', fontsize=12)
    plt.ylabel('Runs Scored', fontsize=12)
    plt.legend()
    plt.grid(True, alpha=0.3)

    # Add match result annotations
    for idx, match in df.iterrows():
        match_num = match['Match_Number']
        result = match['Result']
        plt.annotate(f"M{match_num}: {result[:20]}...",
                    xy=(f"M{match_num}", 0),
                    xytext=(0, -40), textcoords='offset points',
                    ha='center', fontsize=8, rotation=90, alpha=0.7)

    plt.tight_layout()
    plt.savefig('plots/performance_timeline.jpg', dpi=300, bbox_inches='tight')
    plt.close()
    print("\nSaved: plots/performance_timeline.jpg")

# Run extended analysis
print("\n\n" + "="*60)
print("RUNNING EXTENDED ANALYSIS")
print("="*60)

df = pd.read_csv('pakistan_t20i_tri_series_2025_complete.csv')
extended_analysis(df)

most_sixes_team = (
    df.groupby("team1")or("team2")["sixes"]
    .sum()
    .sort_values(ascending=False)
)

most_sixes_team.plot(kind="pie", autopct="%1.1f%%")
plt.title("Most Sixes by Team")
plt.ylabel("")
plt.savefig("figures/most_sixes_team.jpg", dpi=300)
plt.close()

most_sixes_team = (
    df.groupby("team")["sixes"]
    .sum()
    .sort_values(ascending=False)
)

most_sixes_team.plot(kind="pie", autopct="%1.1f%%")
plt.title("Most Sixes by Team")
plt.ylabel("")
plt.savefig("figures/most_sixes_team.jpg", dpi=300)
plt.close()

most_wins = df["Result"].value_counts()

most_wins.plot(kind="bar")
plt.title("Most Wins by Team")
plt.ylabel("Wins")
plt.tight_layout()
plt.savefig("figures/most_wins_by_team.jpg", dpi=300)
plt.close()

highest_team_score = pd.concat([
    df[["Team1", "Team1_Total_Runs"]].rename(columns={"Team1":"Team","Team1_Total_Runs":"Runs"}),
    df[["Team2", "Team2_Total_Runs"]].rename(columns={"Team2":"Team","Team2_Total_Runs":"Runs"})
]).sort_values("Runs", ascending=False).head(10)

highest_team_score.set_index("Team")["Runs"].plot(kind="bar")
plt.title("Highest Team Scores (Single Match)")
plt.ylabel("Runs")
plt.tight_layout()
plt.savefig("figures/highest_team_score.jpg", dpi=300)
plt.close()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import defaultdict, Counter
import re
from datetime import datetime
import warnings
import os
warnings.filterwarnings('ignore')

# Set style for better visualizations
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

class CricketTriSeriesAnalyzer:
    def __init__(self, df):
        self.df = df
        self.players_data = self._extract_players_data()
        self.team_data = self._extract_team_data()

    def _extract_players_data(self):
        """Extract individual player statistics from the dataset"""
        players = defaultdict(lambda: {
            'runs': 0, 'wickets': 0, 'sixes': 0, 'fours': 0,
            'matches': set(), 'ducks': 0, 'catches': 0,
            '30plus_scores': 0, 'player_of_match': 0
        })

        for idx, match in self.df.iterrows():
            # Process both teams
            for team_num in ['Team1', 'Team2']:
                team_name = match[team_num]

                # Extract playing XI
                playing_xi = match[f'{team_num}_Playing_XI'].split(', ')

                # Count catches (approximation from fielding)
                top_wicket_taker = match[f'{team_num}_Top_Wicket_Taker']
                if top_wicket_taker and pd.notna(top_wicket_taker):
                    try:
                        # Extract bowler name and wickets
                        parts = top_wicket_taker.split('/')
                        if len(parts) >= 1:
                            bowler_name = parts[0].strip()
                            # Extract wickets number
                            wickets_match = re.search(r'(\d+)/', top_wicket_taker)
                            if wickets_match and bowler_name in playing_xi:
                                wickets = int(wickets_match.group(1))
                                players[bowler_name]['wickets'] += wickets
                    except:
                        pass

                # Process top scorer
                top_scorer = match[f'{team_num}_Top_Scorer']
                if top_scorer and pd.notna(top_scorer):
                    try:
                        # Extract name and runs from format like "Player Name 49(36)"
                        name_match = re.match(r'([A-Za-z\s\.]+)\s+(\d+)\(', top_scorer)
                        if name_match:
                            name = name_match.group(1).strip()
                            runs = int(name_match.group(2))

                            if name in playing_xi:
                                players[name]['runs'] += runs
                                players[name]['matches'].add(idx)

                                # Count ducks
                                if runs == 0:
                                    players[name]['ducks'] += 1

                                # Count 30+ scores
                                if runs >= 30:
                                    players[name]['30plus_scores'] += 1
                    except:
                        pass

                # Count sixes and fours
                try:
                    team_sixes = match[f'{team_num}_Sixes']
                    team_fours = match[f'{team_num}_Fours']

                    if pd.notna(team_sixes) and team_sixes > 0:
                        # Distribute team sixes among playing XI
                        for player in playing_xi:
                            players[player]['sixes'] += team_sixes / len(playing_xi)

                    if pd.notna(team_fours) and team_fours > 0:
                        for player in playing_xi:
                            players[player]['fours'] += team_fours / len(playing_xi)
                except:
                    pass

        # Count player of match awards
        for idx, match in self.df.iterrows():
            potm = match['Player_of_the_Match']
            if potm and pd.notna(potm):
                players[potm]['player_of_match'] += 1

        return players

    def _extract_team_data(self):
        """Extract team-level statistics"""
        teams = defaultdict(lambda: {
            'matches': 0, 'wins': 0, 'losses': 0, 'total_runs': 0,
            'total_sixes': 0, 'total_fours': 0, 'powerplay_runs': [],
            'toss_wins': 0, 'toss_loss_match_wins': 0
        })

        for idx, match in self.df.iterrows():
            # Count toss statistics
            toss_winner = match['Toss_Winner']
            match_winner = None

            # Extract match winner from result
            result = str(match['Result'])
            if 'won' in result.lower():
                match_winner = result.split(' won')[0].strip()

            # Update toss statistics
            if toss_winner:
                teams[toss_winner]['toss_wins'] += 1

            # Process both teams
            for team_num in ['Team1', 'Team2']:
                team_name = match[team_num]
                teams[team_name]['matches'] += 1

                # Update runs, sixes, fours
                try:
                    teams[team_name]['total_runs'] += match[f'{team_num}_Total_Runs']
                    teams[team_name]['total_sixes'] += match[f'{team_num}_Sixes']
                    teams[team_name]['total_fours'] += match[f'{team_num}_Fours']
                except:
                    pass

                # Track powerplay scores
                if pd.notna(match[f'{team_num}_Powerplay_Runs']):
                    teams[team_name]['powerplay_runs'].append(
                        match[f'{team_num}_Powerplay_Runs']
                    )

                # Count wins and losses
                if match_winner and match_winner == team_name:
                    teams[team_name]['wins'] += 1
                    if team_name != toss_winner:
                        teams[team_name]['toss_loss_match_wins'] += 1
                elif match_winner and match_winner != team_name:
                    teams[team_name]['losses'] += 1

        return teams

    def most_runs_by_player(self):
        """Find player with most runs"""
        runs_data = [(player, data['runs']) for player, data in self.players_data.items()]
        runs_data.sort(key=lambda x: x[1], reverse=True)
        return runs_data[:10]

    def most_wickets_by_player(self):
        """Find player with most wickets"""
        wickets_data = [(player, data['wickets']) for player, data in self.players_data.items()]
        wickets_data.sort(key=lambda x: x[1], reverse=True)
        return wickets_data[:10]

    def most_sixes_by_team(self):
        """Find team with most sixes"""
        sixes_data = [(team, data['total_sixes']) for team, data in self.team_data.items()]
        sixes_data.sort(key=lambda x: x[1], reverse=True)
        return sixes_data

    def most_sixes_by_player(self):
        """Find player with most sixes"""
        sixes_data = [(player, round(data['sixes'])) for player, data in self.players_data.items()]
        sixes_data.sort(key=lambda x: x[1], reverse=True)
        return sixes_data[:10]

    def highest_runs_by_team(self):
        """Find team with highest total runs"""
        runs_data = [(team, data['total_runs']) for team, data in self.team_data.items()]
        runs_data.sort(key=lambda x: x[1], reverse=True)
        return runs_data

    def highest_runs_by_player(self):
        """Find player with highest individual score"""
        player_highest = {}
        for idx, match in self.df.iterrows():
            for team_num in ['Team1', 'Team2']:
                top_scorer = match[f'{team_num}_Top_Scorer']
                if top_scorer and pd.notna(top_scorer):
                    try:
                        name_match = re.match(r'([A-Za-z\s\.]+)\s+(\d+)\(', top_scorer)
                        if name_match:
                            name = name_match.group(1).strip()
                            runs = int(name_match.group(2))
                            if name not in player_highest or runs > player_highest[name]:
                                player_highest[name] = runs
                    except:
                        pass

        highest_data = [(player, score) for player, score in player_highest.items()]
        highest_data.sort(key=lambda x: x[1], reverse=True)
        return highest_data[:10]

    def most_ducks(self):
        """Find player with most ducks"""
        ducks_data = [(player, data['ducks']) for player, data in self.players_data.items()]
        ducks_data.sort(key=lambda x: x[1], reverse=True)
        return [d for d in ducks_data if d[1] > 0][:10]

    def most_30plus_scores(self):
        """Find player with most 30+ scores"""
        scores_data = [(player, data['30plus_scores']) for player, data in self.players_data.items()]
        scores_data.sort(key=lambda x: x[1], reverse=True)
        return [s for s in scores_data if s[1] > 0][:10]

    def highest_powerplay_score(self):
        """Find highest powerplay score by team"""
        powerplay_data = []
        for team, data in self.team_data.items():
            if data['powerplay_runs']:
                powerplay_data.append((team, max(data['powerplay_runs'])))

        powerplay_data.sort(key=lambda x: x[1], reverse=True)
        return powerplay_data

    def toss_impact_analysis(self):
        """Analyze impact of toss on match outcome"""
        toss_wins_match_wins = 0
        total_matches = len(self.df)

        for idx, match in self.df.iterrows():
            toss_winner = match['Toss_Winner']
            match_winner = None

            result = str(match['Result'])
            if 'won' in result.lower():
                match_winner = result.split(' won')[0].strip()

            if toss_winner and toss_winner == match_winner:
                toss_wins_match_wins += 1

        toss_win_percentage = (toss_wins_match_wins / total_matches) * 100 if total_matches > 0 else 0
        return {
            'toss_wins_match_wins': toss_wins_match_wins,
            'total_matches': total_matches,
            'percentage': toss_win_percentage
        }

    def most_wins_by_team(self):
        """Find team with most wins"""
        wins_data = [(team, data['wins']) for team, data in self.team_data.items()]
        wins_data.sort(key=lambda x: x[1], reverse=True)
        return wins_data

    def most_losses_by_team(self):
        """Find team with most losses"""
        losses_data = [(team, data['losses']) for team, data in self.team_data.items()]
        losses_data.sort(key=lambda x: x[1], reverse=True)
        return losses_data

    def most_catches_by_player(self):
        """Find player with most catches (approximated)"""
        catches_data = [(player, data['wickets']) for player, data in self.players_data.items()]
        catches_data.sort(key=lambda x: x[1], reverse=True)
        return catches_data[:10]

    def most_player_of_matches(self):
        """Find player with most Player of Match awards"""
        potm_data = [(player, data['player_of_match']) for player, data in self.players_data.items()]
        potm_data.sort(key=lambda x: x[1], reverse=True)
        return [p for p in potm_data if p[1] > 0]

    # Visualization methods
    def plot_pie_chart(self, data, title, filename):
        """Create and save a pie chart"""
        plt.figure(figsize=(10, 8))
        labels = [item[0] for item in data[:5]]
        values = [item[1] for item in data[:5]]

        plt.pie(values, labels=labels, autopct='%1.1f%%', startangle=90)
        plt.title(f'{title} (Top 5)', fontsize=16, fontweight='bold')
        plt.axis('equal')
        plt.tight_layout()
        plt.savefig(f'plots/{filename}', dpi=300, bbox_inches='tight')
        plt.close()
        print(f"Saved: plots/{filename}")

    def plot_bar_chart(self, data, title, xlabel, ylabel, filename, color='skyblue'):
        """Create and save a bar chart"""
        plt.figure(figsize=(12, 6))
        labels = [item[0] for item in data[:8]]
        values = [item[1] for item in data[:8]]

        bars = plt.bar(labels, values, color=color)
        plt.title(title, fontsize=16, fontweight='bold')
        plt.xlabel(xlabel, fontsize=12)
        plt.ylabel(ylabel, fontsize=12)
        plt.xticks(rotation=45, ha='right')

        # Add value labels on bars
        for bar, value in zip(bars, values):
            plt.text(bar.get_x() + bar.get_width()/2, bar.get_height(),
                    f'{value}', ha='center', va='bottom', fontweight='bold')

        plt.tight_layout()
        plt.savefig(f'plots/{filename}', dpi=300, bbox_inches='tight')
        plt.close()
        print(f"Saved: plots/{filename}")

    def plot_line_chart(self, data, title, xlabel, ylabel, filename):
        """Create and save a line chart"""
        plt.figure(figsize=(12, 6))
        x_labels = [item[0] for item in data[:8]]
        y_values = [item[1] for item in data[:8]]

        plt.plot(x_labels, y_values, marker='o', linewidth=2, markersize=8)
        plt.title(title, fontsize=16, fontweight='bold')
        plt.xlabel(xlabel, fontsize=12)
        plt.ylabel(ylabel, fontsize=12)
        plt.xticks(rotation=45, ha='right')
        plt.grid(True, alpha=0.3)

        # Add value labels
        for i, (label, value) in enumerate(zip(x_labels, y_values)):
            plt.text(i, value + (max(y_values)*0.02), f'{value}',
                    ha='center', va='bottom', fontweight='bold')

        plt.tight_layout()
        plt.savefig(f'plots/{filename}', dpi=300, bbox_inches='tight')
        plt.close()
        print(f"Saved: plots/{filename}")

    def plot_toss_impact(self, toss_data, filename):
        """Create and save toss impact visualization"""
        plt.figure(figsize=(8, 6))

        categories = ['Toss Wins Result\nin Match Wins', 'Toss Loss but\nMatch Wins']
        values = [
            toss_data['toss_wins_match_wins'],
            toss_data['total_matches'] - toss_data['toss_wins_match_wins']
        ]

        colors = ['#4CAF50', '#FF9800']
        bars = plt.bar(categories, values, color=colors)

        plt.title(f'Toss Impact Analysis\n({toss_data["percentage"]:.1f}% of toss winners won matches)',
                 fontsize=14, fontweight='bold')
        plt.ylabel('Number of Matches', fontsize=12)

        # Add value labels
        for bar, value in zip(bars, values):
            plt.text(bar.get_x() + bar.get_width()/2, bar.get_height(),
                    f'{value}', ha='center', va='bottom', fontweight='bold')

        plt.tight_layout()
        plt.savefig(f'plots/{filename}', dpi=300, bbox_inches='tight')
        plt.close()
        print(f"Saved: plots/{filename}")

    def create_summary_report(self):
        """Generate a comprehensive analysis report"""
        print("="*60)
        print("PAKISTAN T20I TRI-SERIES 2025 - COMPREHENSIVE ANALYSIS")
        print("="*60)

        # 1. Most Runs by Player
        print("\n1. TOP 10 RUN SCORERS:")
        print("-"*40)
        runs_data = self.most_runs_by_player()
        for i, (player, runs) in enumerate(runs_data[:10], 1):
            print(f"{i:2}. {player:25} {runs:4} runs")

        # 2. Most Wickets by Player
        print("\n2. TOP 10 WICKET TAKERS:")
        print("-"*40)
        wickets_data = self.most_wickets_by_player()
        for i, (player, wickets) in enumerate(wickets_data[:10], 1):
            print(f"{i:2}. {player:25} {wickets:4} wickets")

        # 3. Most Sixes by Team
        print("\n3. SIXES BY TEAM:")
        print("-"*40)
        sixes_team = self.most_sixes_by_team()
        for team, sixes in sixes_team:
            print(f"{team:15} {sixes:4} sixes")

        # 4. Most Sixes by Player
        print("\n4. TOP 10 SIX HITTERS:")
        print("-"*40)
        sixes_player = self.most_sixes_by_player()
        for i, (player, sixes) in enumerate(sixes_player[:10], 1):
            print(f"{i:2}. {player:25} {sixes:4} sixes")

        # 5. Highest Runs by Team
        print("\n5. TOTAL RUNS BY TEAM:")
        print("-"*40)
        team_runs = self.highest_runs_by_team()
        for team, runs in team_runs:
            print(f"{team:15} {runs:4} runs")

        # 6. Highest Individual Score
        print("\n6. HIGHEST INDIVIDUAL SCORES:")
        print("-"*40)
        highest_scores = self.highest_runs_by_player()
        for i, (player, score) in enumerate(highest_scores[:10], 1):
            print(f"{i:2}. {player:25} {score:4} runs")

        # 7. Most Ducks
        print("\n7. MOST DUCKS:")
        print("-"*40)
        ducks = self.most_ducks()
        for i, (player, duck_count) in enumerate(ducks[:10], 1):
            print(f"{i:2}. {player:25} {duck_count:4} ducks")

        # 8. Most 30+ Scores
        print("\n8. MOST 30+ SCORES:")
        print("-"*40)
        thirty_plus = self.most_30plus_scores()
        for i, (player, count) in enumerate(thirty_plus[:10], 1):
            print(f"{i:2}. {player:25} {count:4} times")

        # 9. Highest Powerplay Score
        print("\n9. HIGHEST POWERPLAY SCORES:")
        print("-"*40)
        powerplay_scores = self.highest_powerplay_score()
        for team, score in powerplay_scores:
            print(f"{team:15} {score:4} runs")

        # 10. Toss Impact
        print("\n10. TOSS IMPACT ANALYSIS:")
        print("-"*40)
        toss_impact = self.toss_impact_analysis()
        print(f"Toss winners who won match: {toss_impact['toss_wins_match_wins']}/{toss_impact['total_matches']}")
        print(f"Percentage: {toss_impact['percentage']:.1f}%")

        # 11. Most Wins by Team
        print("\n11. WINS BY TEAM:")
        print("-"*40)
        wins = self.most_wins_by_team()
        for team, win_count in wins:
            print(f"{team:15} {win_count:4} wins")

        # 12. Most Losses by Team
        print("\n12. LOSSES BY TEAM:")
        print("-"*40)
        losses = self.most_losses_by_team()
        for team, loss_count in losses:
            print(f"{team:15} {loss_count:4} losses")

        # 13. Most Catches (approximated)
        print("\n13. TOP FIELDERS (Wickets as proxy):")
        print("-"*40)
        catches = self.most_catches_by_player()
        for i, (player, catch_count) in enumerate(catches[:10], 1):
            print(f"{i:2}. {player:25} {catch_count:4} wickets")

        # 14. Most Player of Match Awards
        print("\n14. PLAYER OF MATCH AWARDS:")
        print("-"*40)
        potm = self.most_player_of_matches()
        for player, awards in potm:
            print(f"{player:25} {awards:4} awards")

        print("\n" + "="*60)
        print("ANALYSIS COMPLETE - VISUALIZATIONS SAVED TO 'plots/' FOLDER")
        print("="*60)

    def create_all_visualizations(self):
        """Create and save all visualizations"""
        if not os.path.exists('plots'):
            os.makedirs('plots')

        print("\nCreating visualizations...")

        # 1. Pie Chart - Team Win Distribution
        team_wins = self.most_wins_by_team()
        self.plot_pie_chart(team_wins, 'Team Win Distribution', 'team_wins_pie.jpg')

        # 2. Bar Chart - Top Run Scorers
        top_runs = self.most_runs_by_player()
        self.plot_bar_chart(top_runs, 'Top Run Scorers', 'Player', 'Total Runs',
                           'top_runs_bar.jpg', color='#2E86AB')

        # 3. Bar Chart - Top Wicket Takers
        top_wickets = self.most_wickets_by_player()
        self.plot_bar_chart(top_wickets, 'Top Wicket Takers', 'Player', 'Total Wickets',
                           'top_wickets_bar.jpg', color='#A23B72')

        # 4. Bar Chart - Most Sixes by Team
        team_sixes = self.most_sixes_by_team()
        self.plot_bar_chart(team_sixes, 'Most Sixes by Team', 'Team', 'Number of Sixes',
                           'team_sixes_bar.jpg', color='#F18F01')

        # 5. Line Chart - Team Performance (Total Runs)
        team_performance = self.highest_runs_by_team()
        self.plot_line_chart(team_performance, 'Team Batting Performance',
                            'Team', 'Total Runs', 'team_runs_line.jpg')

        # 6. Bar Chart - Most Player of Match Awards
        potm_awards = self.most_player_of_matches()
        self.plot_bar_chart(potm_awards, 'Player of Match Awards',
                           'Player', 'Number of Awards', 'potm_awards_bar.jpg',
                           color='#5C6D70')

        # 7. Bar Chart - Most 30+ Scores
        thirty_plus = self.most_30plus_scores()
        self.plot_bar_chart(thirty_plus, 'Most 30+ Scores', 'Player',
                           'Number of 30+ Scores', 'thirty_plus_bar.jpg',
                           color='#E6AF2E')

        # 8. Toss Impact Analysis
        toss_data = self.toss_impact_analysis()
        self.plot_toss_impact(toss_data, 'toss_impact_bar.jpg')

        # 9. Comparison Chart - Team Statistics
        self.create_team_comparison_chart()

        # 10. Player Performance Dashboard
        self.create_player_performance_dashboard()

        print("\nAll visualizations saved successfully!")

    def create_team_comparison_chart(self):
        """Create a comprehensive team comparison chart"""
        fig, axes = plt.subplots(2, 2, figsize=(15, 12))

        # Data preparation
        teams = list(self.team_data.keys())

        # 1. Wins vs Losses
        wins = [self.team_data[team]['wins'] for team in teams]
        losses = [self.team_data[team]['losses'] for team in teams]

        x = np.arange(len(teams))
        width = 0.35

        axes[0, 0].bar(x - width/2, wins, width, label='Wins', color='#4CAF50')
        axes[0, 0].bar(x + width/2, losses, width, label='Losses', color='#F44336')
        axes[0, 0].set_title('Team Wins vs Losses', fontsize=14, fontweight='bold')
        axes[0, 0].set_xlabel('Team')
        axes[0, 0].set_ylabel('Count')
        axes[0, 0].set_xticks(x)
        axes[0, 0].set_xticklabels(teams)
        axes[0, 0].legend()

        # 2. Total Runs
        total_runs = [self.team_data[team]['total_runs'] for team in teams]
        axes[0, 1].bar(teams, total_runs, color='#2196F3')
        axes[0, 1].set_title('Total Runs Scored', fontsize=14, fontweight='bold')
        axes[0, 1].set_xlabel('Team')
        axes[0, 1].set_ylabel('Runs')

        # 3. Sixes and Fours
        sixes = [self.team_data[team]['total_sixes'] for team in teams]
        fours = [self.team_data[team]['total_fours'] for team in teams]

        axes[1, 0].bar(teams, sixes, label='Sixes', color='#FF9800')
        axes[1, 0].bar(teams, fours, bottom=sixes, label='Fours', color='#9C27B0')
        axes[1, 0].set_title('Boundaries Hit (Sixes & Fours)', fontsize=14, fontweight='bold')
        axes[1, 0].set_xlabel('Team')
        axes[1, 0].set_ylabel('Count')
        axes[1, 0].legend()

        # 4. Win Percentage
        win_percentage = []
        for team in teams:
            matches = self.team_data[team]['matches']
            wins = self.team_data[team]['wins']
            percentage = (wins / matches * 100) if matches > 0 else 0
            win_percentage.append(percentage)

        axes[1, 1].bar(teams, win_percentage, color=['#4CAF50' if p > 50 else '#F44336' for p in win_percentage])
        axes[1, 1].set_title('Win Percentage', fontsize=14, fontweight='bold')
        axes[1, 1].set_xlabel('Team')
        axes[1, 1].set_ylabel('Percentage (%)')

        plt.suptitle('Team Performance Comparison - Pakistan T20I Tri-Series 2025',
                    fontsize=16, fontweight='bold', y=1.02)
        plt.tight_layout()
        plt.savefig('plots/team_comparison.jpg', dpi=300, bbox_inches='tight')
        plt.close()
        print("Saved: plots/team_comparison.jpg")

    def create_player_performance_dashboard(self):
        """Create a player performance dashboard"""
        fig, axes = plt.subplots(2, 2, figsize=(16, 12))

        # 1. Top 5 Run Scorers
        top_runs = self.most_runs_by_player()[:5]
        players_runs = [p[0] for p in top_runs]
        runs = [p[1] for p in top_runs]

        bars1 = axes[0, 0].bar(players_runs, runs, color='#2E86AB')
        axes[0, 0].set_title('Top 5 Run Scorers', fontsize=14, fontweight='bold')
        axes[0, 0].set_xlabel('Player')
        axes[0, 0].set_ylabel('Runs')
        axes[0, 0].tick_params(axis='x', rotation=45)

        # Add value labels
        for bar, value in zip(bars1, runs):
            axes[0, 0].text(bar.get_x() + bar.get_width()/2, bar.get_height(),
                           f'{value}', ha='center', va='bottom', fontweight='bold')

        # 2. Top 5 Wicket Takers
        top_wickets = self.most_wickets_by_player()[:5]
        players_wickets = [p[0] for p in top_wickets]
        wickets = [p[1] for p in top_wickets]

        bars2 = axes[0, 1].bar(players_wickets, wickets, color='#A23B72')
        axes[0, 1].set_title('Top 5 Wicket Takers', fontsize=14, fontweight='bold')
        axes[0, 1].set_xlabel('Player')
        axes[0, 1].set_ylabel('Wickets')
        axes[0, 1].tick_params(axis='x', rotation=45)

        # Add value labels
        for bar, value in zip(bars2, wickets):
            axes[0, 1].text(bar.get_x() + bar.get_width()/2, bar.get_height(),
                           f'{value}', ha='center', va='bottom', fontweight='bold')

        # 3. Player of Match Awards
        potm = self.most_player_of_matches()
        if len(potm) > 5:
            potm = potm[:5]
        players_potm = [p[0] for p in potm]
        awards = [p[1] for p in potm]

        bars3 = axes[1, 0].bar(players_potm, awards, color='#5C6D70')
        axes[1, 0].set_title('Player of Match Awards', fontsize=14, fontweight='bold')
        axes[1, 0].set_xlabel('Player')
        axes[1, 0].set_ylabel('Awards')
        axes[1, 0].tick_params(axis='x', rotation=45)

        # Add value labels
        for bar, value in zip(bars3, awards):
            axes[1, 0].text(bar.get_x() + bar.get_width()/2, bar.get_height(),
                           f'{value}', ha='center', va='bottom', fontweight='bold')

        # 4. 30+ Scores
        thirty_plus = self.most_30plus_scores()
        if len(thirty_plus) > 5:
            thirty_plus = thirty_plus[:5]
        players_30 = [p[0] for p in thirty_plus]
        scores_30 = [p[1] for p in thirty_plus]

        bars4 = axes[1, 1].bar(players_30, scores_30, color='#E6AF2E')
        axes[1, 1].set_title('Most 30+ Scores', fontsize=14, fontweight='bold')
        axes[1, 1].set_xlabel('Player')
        axes[1, 1].set_ylabel('Number of 30+ Scores')
        axes[1, 1].tick_params(axis='x', rotation=45)

        # Add value labels
        for bar, value in zip(bars4, scores_30):
            axes[1, 1].text(bar.get_x() + bar.get_width()/2, bar.get_height(),
                           f'{value}', ha='center', va='bottom', fontweight='bold')

        plt.suptitle('Player Performance Dashboard - Pakistan T20I Tri-Series 2025',
                    fontsize=16, fontweight='bold', y=1.02)
        plt.tight_layout()
        plt.savefig('plots/player_dashboard.jpg', dpi=300, bbox_inches='tight')
        plt.close()
        print("Saved: plots/player_dashboard.jpg")

    def export_results_to_csv(self):
        """Export all analysis results to CSV files"""
        if not os.path.exists('results'):
            os.makedirs('results')

        # Export player statistics
        player_stats = []
        for player, stats in self.players_data.items():
            player_stats.append({
                'Player': player,
                'Total_Runs': stats['runs'],
                'Total_Wickets': stats['wickets'],
                'Sixes': round(stats['sixes']),
                'Fours': round(stats['fours']),
                'Matches_Played': len(stats['matches']),
                'Ducks': stats['ducks'],
                '30Plus_Scores': stats['30plus_scores'],
                'Player_of_Match_Awards': stats['player_of_match']
            })

        player_df = pd.DataFrame(player_stats)
        player_df = player_df.sort_values('Total_Runs', ascending=False)
        player_df.to_csv('results/player_statistics.csv', index=False)
        print("Saved: results/player_statistics.csv")

        # Export team statistics
        team_stats = []
        for team, stats in self.team_data.items():
            team_stats.append({
                'Team': team,
                'Matches_Played': stats['matches'],
                'Wins': stats['wins'],
                'Losses': stats['losses'],
                'Win_Percentage': (stats['wins']/stats['matches']*100) if stats['matches'] > 0 else 0,
                'Total_Runs': stats['total_runs'],
                'Total_Sixes': stats['total_sixes'],
                'Total_Fours': stats['total_fours'],
                'Average_Powerplay_Score': np.mean(stats['powerplay_runs']) if stats['powerplay_runs'] else 0,
                'Toss_Wins': stats['toss_wins'],
                'Wins_After_Toss_Loss': stats['toss_loss_match_wins']
            })

        team_df = pd.DataFrame(team_stats)
        team_df = team_df.sort_values('Wins', ascending=False)
        team_df.to_csv('results/team_statistics.csv', index=False)
        print("Saved: results/team_statistics.csv")

        # Export top performers
        top_performers = {
            'Top_Run_Scorers': self.most_runs_by_player()[:10],
            'Top_Wicket_Takers': self.most_wickets_by_player()[:10],
            'Most_Player_of_Match': self.most_player_of_matches(),
            'Most_Sixes_Player': self.most_sixes_by_player()[:10],
            'Most_30Plus_Scores': self.most_30plus_scores()[:10],
            'Most_Ducks': self.most_ducks()[:10]
        }

        with open('results/top_performers_summary.txt', 'w') as f:
            f.write("TOP PERFORMERS - PAKISTAN T20I TRI-SERIES 2025\n")
            f.write("="*60 + "\n\n")

            for category, performers in top_performers.items():
                f.write(f"\n{category.replace('_', ' ').title()}:\n")
                f.write("-"*40 + "\n")
                for i, (player, value) in enumerate(performers, 1):
                    f.write(f"{i:2}. {player:25} {value}\n")

        print("Saved: results/top_performers_summary.txt")

# Extended Analysis Functions
def extended_analysis(df):
    """Perform extended analysis with more specific queries"""

    print("\n" + "="*60)
    print("EXTENDED ANALYSIS")
    print("="*60)

    # Create analyzer
    analyzer = CricketTriSeriesAnalyzer(df)

    # 1. Match-by-Match Analysis
    print("\n1. MATCH-BY-MATCH DETAILED ANALYSIS:")
    print("-"*60)

    match_details = []
    for idx, match in df.iterrows():
        match_info = {
            'Match': match['Match_Number'],
            'Date': match['Date'],
            'Teams': f"{match['Team1']} vs {match['Team2']}",
            'Toss': f"{match['Toss_Winner']} ({match['Toss_Decision']})",
            'Result': match['Result'],
            'POTM': match['Player_of_the_Match'],
            'Team1_Score': match['Team1_Score'],
            'Team2_Score': match['Team2_Score']
        }
        match_details.append(match_info)

    match_df = pd.DataFrame(match_details)
    print(match_df.to_string(index=False))

    # 2. Close Match Analysis
    print("\n\n2. CLOSE MATCHES ANALYSIS:")
    print("-"*60)

    close_matches = []
    for idx, match in df.iterrows():
        result = str(match['Result'])
        if 'won by' in result:
            try:
                margin = int(re.findall(r'\d+', result.split('by')[1])[0])
                if 'wickets' in result and margin <= 3:
                    close_matches.append((match['Match_Number'], result))
                elif 'runs' in result and margin <= 20:
                    close_matches.append((match['Match_Number'], result))
            except:
                pass

    if close_matches:
        for match_num, result in close_matches:
            print(f"Match {match_num}: {result}")
    else:
        print("No close matches found")

    # 3. Individual Match Highs and Lows
    print("\n\n3. INDIVIDUAL MATCH HIGHLIGHTS:")
    print("-"*60)

    # Highest team total
    highest_total = 0
    highest_match = ""
    for idx, match in df.iterrows():
        for team in ['Team1', 'Team2']:
            runs = match[f'{team}_Total_Runs']
            if runs > highest_total:
                highest_total = runs
                highest_match = f"Match {match['Match_Number']}: {match[team]}"

    print(f"Highest Team Total: {highest_total} runs ({highest_match})")

    # Lowest team total
    lowest_total = float('inf')
    lowest_match = ""
    for idx, match in df.iterrows():
        for team in ['Team1', 'Team2']:
            runs = match[f'{team}_Total_Runs']
            if runs < lowest_total:
                lowest_total = runs
                lowest_match = f"Match {match['Match_Number']}: {match[team]}"

    print(f"Lowest Team Total: {lowest_total} runs ({lowest_match})")

    # 4. Powerplay Analysis
    print("\n\n4. POWERPLAY PERFORMANCE ANALYSIS:")
    print("-"*60)

    powerplay_stats = defaultdict(list)
    for idx, match in df.iterrows():
        for team in ['Team1', 'Team2']:
            team_name = match[team]
            pp_runs = match[f'{team}_Powerplay_Runs']
            if pd.notna(pp_runs):
                powerplay_stats[team_name].append(pp_runs)

    for team, scores in powerplay_stats.items():
        if scores:
            avg_pp = np.mean(scores)
            max_pp = max(scores)
            min_pp = min(scores)
            print(f"{team:15} Avg: {avg_pp:.1f}, Max: {max_pp}, Min: {min_pp}")

    # 5. Extras Analysis
    print("\n\n5. EXTRAS ANALYSIS:")
    print("-"*60)

    extras_by_team = defaultdict(lambda: {'total': 0, 'wides': 0, 'noballs': 0})
    for idx, match in df.iterrows():
        for team in ['Team1', 'Team2']:
            team_name = match[team]
            extras = match.get(f'{team}_Extras', 0)
            wides = match.get(f'{team}_Wides', 0)
            noballs = match.get(f'{team}_No_Balls', 0)

            if pd.notna(extras):
                extras_by_team[team_name]['total'] += extras
            if pd.notna(wides):
                extras_by_team[team_name]['wides'] += wides
            if pd.notna(noballs):
                extras_by_team[team_name]['noballs'] += noballs

    for team, data in extras_by_team.items():
        print(f"{team:15} Total Extras: {data['total']}, Wides: {data['wides']}, No Balls: {data['noballs']}")

    # 6. Create Performance Timeline
    create_performance_timeline(df)

    # 7. Head-to-Head Records
    print("\n\n6. HEAD-TO-HEAD RECORDS:")
    print("-"*60)

    h2h = defaultdict(lambda: defaultdict(lambda: {'wins': 0, 'losses': 0}))
    for idx, match in df.iterrows():
        team1 = match['Team1']
        team2 = match['Team2']
        result = str(match['Result'])

        if 'won' in result:
            winner = result.split(' won')[0].strip()
            loser = team2 if winner == team1 else team1

            h2h[winner][loser]['wins'] += 1
            h2h[loser][winner]['losses'] += 1

    teams = list(set(df['Team1'].tolist() + df['Team2'].tolist()))
    for i, team1 in enumerate(teams):
        for j, team2 in enumerate(teams[i+1:], i+1):
            wins_1 = h2h[team1][team2]['wins']
            wins_2 = h2h[team2][team1]['wins']
            if wins_1 > 0 or wins_2 > 0:
                print(f"{team1:15} vs {team2:15}: {wins_1}-{wins_2}")

def create_performance_timeline(df):
    """Create match performance timeline"""
    plt.figure(figsize=(15, 8))

    # Extract match timeline data
    matches = []
    pakistan_scores = []
    srilanka_scores = []
    zimbabwe_scores = []

    for idx, match in df.iterrows():
        match_num = match['Match_Number']
        matches.append(f"M{match_num}")

        # Get scores for each team
        for team in ['Team1', 'Team2']:
            team_name = match[team]
            score = match[f'{team}_Total_Runs']

            if team_name == 'Pakistan':
                pakistan_scores.append(score)
            elif team_name == 'Sri Lanka':
                srilanka_scores.append(score)
            elif team_name == 'Zimbabwe':
                zimbabwe_scores.append(score)

    # Plot timeline
    if pakistan_scores:
        plt.plot(range(1, len(pakistan_scores) + 1), pakistan_scores, marker='o',
                 label='Pakistan', linewidth=2, markersize=8)
    if srilanka_scores:
        plt.plot(range(1, len(srilanka_scores) + 1), srilanka_scores, marker='s',
                 label='Sri Lanka', linewidth=2, markersize=8)
    if zimbabwe_scores:
        plt.plot(range(1, len(zimbabwe_scores) + 1), zimbabwe_scores, marker='^',
                 label='Zimbabwe', linewidth=2, markersize=8)

    plt.title('Team Performance Timeline - Runs Scored per Match',
              fontsize=16, fontweight='bold')
    plt.xlabel('Match Number', fontsize=12)
    plt.ylabel('Runs Scored', fontsize=12)
    plt.legend()
    plt.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig('plots/performance_timeline.jpg', dpi=300, bbox_inches='tight')
    plt.close()
    print("\nSaved: plots/performance_timeline.jpg")

# Main execution function
def main():
    # Load the dataset
    print("Loading dataset...")
    try:
        df = pd.read_csv('pakistan_t20i_tri_series_2025_complete.csv')
        print(f"Dataset loaded successfully! Shape: {df.shape}")
    except FileNotFoundError:
        print("Error: Dataset file not found!")
        print("Please ensure 'pakistan_t20i_tri_series_2025_complete.csv' is in the current directory")
        return

    # Create analyzer instance
    analyzer = CricketTriSeriesAnalyzer(df)

    # Generate comprehensive report
    analyzer.create_summary_report()

    # Create all visualizations
    analyzer.create_all_visualizations()

    # Export results to CSV
    analyzer.export_results_to_csv()

    # Additional queries
    print("\n" + "="*60)
    print("ADDITIONAL ANALYSIS QUERIES")
    print("="*60)

    # Query 1: Team with best batting average
    print("\n1. Team Batting Averages:")
    print("-"*40)
    for team, data in analyzer.team_data.items():
        avg_runs = data['total_runs'] / data['matches'] if data['matches'] > 0 else 0
        print(f"{team:15} {avg_runs:.1f} runs per match")

    # Query 2: Most consistent player
    print("\n2. Most Consistent Players (Average Runs per Match):")
    print("-"*40)
    player_avg = []
    for player, data in analyzer.players_data.items():
        matches = len(data['matches'])
        if matches > 0:
            avg = data['runs'] / matches
            player_avg.append((player, avg, matches))

    player_avg.sort(key=lambda x: x[1], reverse=True)
    for i, (player, avg, matches) in enumerate(player_avg[:10], 1):
        print(f"{i:2}. {player:25} {avg:.1f} avg ({matches} matches)")

    # Query 3: Best bowling economy
    print("\n3. Best Bowling Economy (Wickets per Match):")
    print("-"*40)
    player_economy = []
    for player, data in analyzer.players_data.items():
        matches = len(data['matches'])
        if matches > 0 and data['wickets'] > 0:
            economy = data['wickets'] / matches
            player_economy.append((player, economy, data['wickets'], matches))

    player_economy.sort(key=lambda x: x[1], reverse=True)
    for i, (player, economy, wickets, matches) in enumerate(player_economy[:10], 1):
        print(f"{i:2}. {player:25} {economy:.1f} wpm ({wickets} wickets in {matches} matches)")

    # Query 4: Tournament timeline
    print("\n4. Tournament Timeline - Match Results:")
    print("-"*40)
    for idx, match in df.iterrows():
        match_num = match['Match_Number']
        team1 = match['Team1']
        team2 = match['Team2']
        result = match['Result']
        date = match['Date']
        print(f"Match {match_num} ({date}): {team1} vs {team2}")
        print(f"  Result: {result}")
        print(f"  Player of Match: {match['Player_of_the_Match']}")

    # Run extended analysis
    extended_analysis(df)

    print("\n" + "="*60)
    print("ANALYSIS COMPLETED SUCCESSFULLY!")
    print("="*60)
    print("\nFiles Generated:")
    print("- Visualizations saved in 'plots/' folder")
    print("- Data exports saved in 'results/' folder")
    print("- Total files created: 15+ visualizations and data files")

# Run the main analysis
if __name__ == "__main__":
    main()

most_fours_team = (
    df.groupby("Team1")["Team1_Fours"].sum()
    .add(df.groupby("Team2")["Team2_Fours"].sum(), fill_value=0)
    .sort_values(ascending=False)
)

most_fours_team.plot(kind="bar")
plt.title("Most Fours by Team")
plt.ylabel("Fours")
plt.tight_layout()
plt.savefig("figures/most_fours_team.jpg", dpi=300)
plt.close()

most_extras = (
    df.groupby("Team1")["Team1_Extras"].sum()
    .add(df.groupby("Team2")["Team2_Extras"].sum(), fill_value=0)
    .sort_values(ascending=False)
)

most_extras.plot(kind="bar")
plt.title("Most Extras Conceded by Team")
plt.ylabel("Extras")
plt.tight_layout()
plt.savefig("figures/most_extras_team.jpg", dpi=300)
plt.close()

highest_powerplay = pd.concat([
    df[["Team1", "Team1_Powerplay_Runs"]].rename(columns={"Team1":"Team","Team1_Powerplay_Runs":"Runs"}),
    df[["Team2", "Team2_Powerplay_Runs"]].rename(columns={"Team2":"Team","Team2_Powerplay_Runs":"Runs"})
]).sort_values("Runs", ascending=False).head(10)

highest_powerplay.set_index("Team")["Runs"].plot(kind="bar")
plt.title("Highest Powerplay Scores by Team")
plt.ylabel("Runs")
plt.tight_layout()
plt.savefig("figures/highest_powerplay_score.jpg", dpi=300)
plt.close()

powerplay = pd.concat([
    df[["Team1", "Team1_Powerplay_Runs"]].rename(columns={"Team1":"Team","Team1_Powerplay_Runs":"Runs"}),
    df[["Team2", "Team2_Powerplay_Runs"]].rename(columns={"Team2":"Team","Team2_Powerplay_Runs":"Runs"})
]).sort_values("Runs", ascending=False).head(10)

powerplay.set_index("Team")["Runs"].plot(kind="bar")
plt.title("Highest Powerplay Scores")
plt.ylabel("Runs")
plt.tight_layout()
plt.savefig("figures/highest_powerplay.jpg", dpi=300)
plt.close()

top_wicket = pd.concat([
    df["Team1_Top_Wicket_Taker"],
    df["Team2_Top_Wicket_Taker"]
]).value_counts().head(10)

top_wicket.plot(kind="bar")
plt.title("Most Times Top Wicket-Taker")
plt.ylabel("Matches")
plt.tight_layout()
plt.savefig("figures/most_top_wicket_taker.jpg", dpi=300)
plt.close()

top_scorer = pd.concat([
    df["Team1_Top_Scorer"],
    df["Team2_Top_Scorer"]
]).value_counts().head(10)

top_scorer.plot(kind="bar")
plt.title("Most Times Top Scorer")
plt.ylabel("Matches")
plt.tight_layout()
plt.savefig("figures/most_top_scorer.jpg", dpi=300)
plt.close()

team1_allout = df[df["Team1_Wickets"] == 10]["Team1"].value_counts()
team2_allout = df[df["Team2_Wickets"] == 10]["Team2"].value_counts()

team_allout = team1_allout.add(team2_allout, fill_value=0).sort_values(ascending=False)

team_allout.plot(kind="bar")
plt.title("Teams All-Out Most Times")
plt.ylabel("All-Out Occurrences")
plt.tight_layout()
plt.savefig("figures/team_allout_most.jpg", dpi=300)
plt.close()

umpires = (
    df["Umpires"]
    .str.split(",", expand=True)
    .stack()
    .str.strip()
    .value_counts()
    .head(10)
)

umpires.plot(kind="bar")
plt.title("Most Frequent Umpires")
plt.ylabel("Matches Officiated")
plt.tight_layout()
plt.savefig("figures/most_umpire_appearances.jpg", dpi=300)
plt.close()

toss_decision = df.groupby("Toss_Decision")["Result"].count()

toss_decision.plot(kind="pie", autopct="%1.1f%%")
plt.title("Toss Decision Distribution")
plt.ylabel("")
plt.savefig("figures/toss_decision_distribution.jpg", dpi=300)
plt.close()

extras = pd.concat([df["Team1_Extras"], df["Team2_Extras"]])
totals = pd.concat([df["Team1_Total_Runs"], df["Team2_Total_Runs"]])

plt.scatter(extras, totals)
plt.title("Extras vs Total Runs")
plt.xlabel("Extras")
plt.ylabel("Total Runs")
plt.tight_layout()
plt.savefig("figures/extras_vs_runs.jpg", dpi=300)
plt.close()

meta_info = {
    "Number of Matches": len(df),
    "Number of Columns": len(df.columns),
    "Start Date": df["Date"].min(),
    "End Date": df["Date"].max(),
    "Teams Involved": ", ".join(sorted(set(df["Team1"]).union(set(df["Team2"])))),
    "Venues": df["Venue"].nunique(),
    "Series": df["Series"].iloc[0]
}

meta_df = pd.DataFrame(meta_info.items(), columns=["Attribute", "Value"])

fig, ax = plt.subplots(figsize=(10, 4))
ax.axis("off")
table = ax.table(
    cellText=meta_df.values,
    colLabels=meta_df.columns,
    loc="center"
)
table.auto_set_font_size(False)
table.set_fontsize(10)
table.scale(1, 1.5)

plt.title("Dataset Metadata Summary", pad=20)
plt.savefig("figures/dataset_metadata_summary.jpg", dpi=300, bbox_inches="tight")
plt.close()

col_meta = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.astype(str)
})

fig, ax = plt.subplots(figsize=(10, 6))
ax.axis("off")
table = ax.table(
    cellText=col_meta.values,
    colLabels=col_meta.columns,
    loc="center"
)
table.auto_set_font_size(False)
table.set_fontsize(8)
table.scale(1, 1.2)

plt.title("Column-Level Metadata (Schema Overview)", pad=20)
plt.savefig("figures/column_metadata.jpg", dpi=300, bbox_inches="tight")
plt.close()